SwissDataScienceCenter/renku-graph

helm-chart/renku-graph/templates/_helpers.tpl
helm-chart/renku-graph/templates/deployment.yaml

Simple update of chart configurations -- namely to work with a public renku deployment

update charts for renku deployment

---

graph-commons/src/main/scala/ch/datascience/http/server/HttpServer.scala
graph-commons/src/test/scala/ch/datascience/http/server/HttpServerSpec.scala
token-repository/src/main/scala/ch/datascience/tokenrepository/repository/association/AssociateTokenEndpoint.scala
token-repository/src/test/scala/ch/datascience/tokenrepository/repository/association/AssociateTokenEndpointSpec.scala
token-repository/src/test/scala/ch/datascience/tokenrepository/repository/deletion/DeleteTokenEndpointSpec.scala
token-repository/src/test/scala/ch/datascience/tokenrepository/repository/fetching/FetchTokenEndpointSpec.scala
webhook-service/src/main/scala/ch/datascience/webhookservice/eventprocessing/HookEventEndpoint.scala
webhook-service/src/main/scala/ch/datascience/webhookservice/hookcreation/HookCreationEndpoint.scala
webhook-service/src/main/scala/ch/datascience/webhookservice/hookvalidation/HookValidationEndpoint.scala
webhook-service/src/test/scala/ch/datascience/webhookservice/eventprocessing/HookEventEndpointSpec.scala
webhook-service/src/test/scala/ch/datascience/webhookservice/hookcreation/HookCreationEndpointSpec.scala
webhook-service/src/test/scala/ch/datascience/webhookservice/hookvalidation/HookValidationEndpointSpec.scala

closes #49  and is described there in details.

Assured all the HTTP responses from the services are JSON

---

graph-commons/src/test/scala/ch/datascience/control/ThrottlerSpec.scala
triples-generator/build.sbt
triples-generator/src/main/scala/ch/datascience/triplesgenerator/eventprocessing/DbEventProcessorRunner.scala
triples-generator/src/test/scala/ch/datascience/triplesgenerator/eventprocessing/DbEventProcessorRunnerSpec.scala

Flaky tests fixes

---

graph-commons/build.sbt
graph-commons/src/main/scala/ch/datascience/http/client/IORestClient.scala
graph-commons/src/test/scala/ch/datascience/generators/Generators.scala
graph-commons/src/test/scala/ch/datascience/http/server/HttpServerSpec.scala
triples-generator/src/main/scala/ch/datascience/triplesgenerator/eventprocessing/CommitEventProcessor.scala
triples-generator/src/main/scala/ch/datascience/triplesgenerator/eventprocessing/TriplesUploader.scala
triples-generator/src/test/scala/ch/datascience/triplesgenerator/eventprocessing/CommitEventProcessorSpec.scala
triples-generator/src/test/scala/ch/datascience/triplesgenerator/eventprocessing/TriplesUploaderSpec.scala

fix: so syntactically invalid triples are not re-delivered to Jena

---

acceptance-tests/src/test/scala/ch/datascience/graph/acceptancetests/LineageQuerySpec.scala
graph-commons/src/test/scala/ch/datascience/rdfstore/RdfStoreData.scala
knowledge-graph/src/main/scala/ch/datascience/knowledgegraph/graphql/lineage/LineageFinder.scala
knowledge-graph/src/main/scala/ch/datascience/knowledgegraph/graphql/lineage/QueryFields.scala
knowledge-graph/src/test/scala/ch/datascience/knowledgegraph/graphql/QuerySchemaSpec.scala
knowledge-graph/src/test/scala/ch/datascience/knowledgegraph/graphql/lineage/IOLineageFinderSpec.scala
knowledge-graph/src/test/scala/ch/datascience/knowledgegraph/graphql/lineage/LineageGenerators.scala

refactor: commitId and filePath as mandatory when querying lineage

---

.travis/travis-publish.sh
.travis/travis-release.sh

Merges to master should also push charts/images.

build: push charts on merges to master

---

graph-commons/build.sbt
triples-generator/build.sbt

This PR is about libs upgrades. No major changes among dependencies.

Libs upgrade

---

acceptance-tests/src/test/scala/ch/datascience/graph/acceptancetests/PushEventsConsumptionSpec.scala
graph-commons/src/main/scala/ch/datascience/control/RateLimit.scala
graph-commons/src/test/scala/ch/datascience/control/RateLimitSpec.scala
knowledge-graph/src/test/scala/ch/datascience/knowledgegraph/graphql/lineage/modelSpec.scala
webhook-service/src/main/scala/ch/datascience/webhookservice/missedevents/EventsSynchronizationThrottler.scala
webhook-service/src/test/scala/ch/datascience/webhookservice/missedevents/EventsSynchronizationThrottlerSpec.scala

This PR fixes some annoying intermittent test failures.

Fixes for intermittent tests failures

---

knowledge-graph/src/main/scala/ch/datascience/knowledgegraph/graphql/lineage/LineageFinder.scala

This PR fixes the bug described in #119 causing the `There are orphan nodes` exception being raised when it's not necessary.
Closes #119

fix: for the lineage query raising the 'There are orphan nodes' error

---

helm-chart/renku-graph/Chart.yaml
helm-chart/renku-graph/charts/jena/templates/fuseki-server.yaml
version.sbt

It looks that there is another `tdb.lock` file in the `/fuseki/system` to be cleaned-up. This PR does the removal of the file too.

Jena startup script

---

.travis/travis-functions.sh
.travis/travis-publish.sh

This PR provides changes to satisfy #184 
closes #184

renku-graph release process to update version of renku-graph in renku's requirements.yaml

---

knowledge-graph/README.md
knowledge-graph/src/main/scala/ch/datascience/knowledgegraph/datasets/rest/DatasetsSearchEndpoint.scala
knowledge-graph/src/main/scala/ch/datascience/knowledgegraph/datasets/rest/ProjectDatasetsEndpoint.scala
knowledge-graph/src/test/scala/ch/datascience/knowledgegraph/datasets/rest/DatasetsSearchEndpointSpec.scala
knowledge-graph/src/test/scala/ch/datascience/knowledgegraph/datasets/rest/ProjectDatasetsEndpointSpec.scala

[WIP] Paging

---

helm-chart/renku-graph/Chart.yaml
knowledge-graph/Dockerfile
knowledge-graph/src/main/scala/ch/datascience/knowledgegraph/datasets/CreatorsFinder.scala
knowledge-graph/src/test/scala/ch/datascience/knowledgegraph/datasets/CreatorsFinderSpec.scala
token-repository/Dockerfile
triples-generator/Dockerfile
version.sbt
webhook-service/Dockerfile

This PR fixes the bug reported in #193 and also forces `UTC` timezone on the microservices boxes.
closes #193

Affiliation bug

---

helm-chart/renku-graph/Chart.yaml
triples-generator/src/main/scala/ch/datascience/triplesgenerator/eventprocessing/CommitEventProcessor.scala
version.sbt

This PR adds some custom buckets for the events processing times metric.

Buckets for events processing times metric

---

helm-chart/renku-graph/Chart.yaml
triples-generator/src/main/scala/ch/datascience/triplesgenerator/reprovisioning/TriplesVersionFinder.scala
triples-generator/src/test/scala/ch/datascience/triplesgenerator/reprovisioning/IOTriplesVersionFinderSpec.scala
version.sbt

Renku version bug

---

graph-commons/src/main/scala/ch/datascience/rdfstore/SparqlValueEncoder.scala
graph-commons/src/test/scala/ch/datascience/generators/CommonGraphGenerators.scala
graph-commons/src/test/scala/ch/datascience/graph/model/projectsSpec.scala
graph-commons/src/test/scala/ch/datascience/rdfstore/InMemoryRdfStore.scala
graph-commons/src/test/scala/ch/datascience/rdfstore/SparqlValueEncoderSpec.scala
triples-generator/src/main/scala/ch/datascience/triplesgenerator/Microservice.scala
triples-generator/src/main/scala/ch/datascience/triplesgenerator/eventprocessing/triplescuration/PersonDetailsUpdater.scala
triples-generator/src/main/scala/ch/datascience/triplesgenerator/metrics/EventLogMetrics.scala
triples-generator/src/test/scala/ch/datascience/triplesgenerator/MicroserviceRunnerSpec.scala
triples-generator/src/test/scala/ch/datascience/triplesgenerator/eventprocessing/triplescuration/PersonDetailsUpdaterQueriesSpec.scala
triples-generator/src/test/scala/ch/datascience/triplesgenerator/eventprocessing/triplescuration/PersonDetailsUpdaterSpec.scala
triples-generator/src/test/scala/ch/datascience/triplesgenerator/metrics/EventLogMetricsSpec.scala

fix: person details updates in KG to work with emails with special chars

---

triples-generator/src/main/scala/ch/datascience/triplesgenerator/eventprocessing/triplesgeneration/renkulog/Commands.scala
triples-generator/src/test/scala/ch/datascience/triplesgenerator/eventprocessing/triplesgeneration/renkulog/GitSpec.scala

fix: for git clone to be recoverable if rails with 'remote hang up'

---

helm-chart/renku-graph/templates/knowledge-graph-deployment.yaml
helm-chart/renku-graph/templates/token-repository-deployment.yaml
helm-chart/renku-graph/templates/triples-generator-deployment.yaml
helm-chart/renku-graph/templates/webhook-service-deployment.yaml
helm-chart/renku-graph/values.yaml

feat: introduced jvmXmx value in the helm templates for all the services

---

acceptance-tests/src/test/scala/ch/datascience/graph/acceptancetests/EventsProcessingStatusSpec.scala
acceptance-tests/src/test/scala/ch/datascience/graph/acceptancetests/stubs/GitLab.scala
acceptance-tests/src/test/scala/ch/datascience/graph/acceptancetests/testing/AcceptanceTestPatience.scala
db-event-log/src/main/scala/ch/datascience/dbeventlog/commands/EventLogAdd.scala
db-event-log/src/main/scala/ch/datascience/dbeventlog/commands/EventLogProcessingStatus.scala
db-event-log/src/main/scala/ch/datascience/dbeventlog/commands/EventLogReScheduler.scala
db-event-log/src/main/scala/ch/datascience/dbeventlog/commands/package.scala
db-event-log/src/main/scala/ch/datascience/dbeventlog/init/BatchDateAdder.scala
db-event-log/src/main/scala/ch/datascience/dbeventlog/init/EventLogDbInitializer.scala
db-event-log/src/main/scala/ch/datascience/dbeventlog/init/ProjectPathAdder.scala
db-event-log/src/main/scala/ch/datascience/dbeventlog/init/package.scala
db-event-log/src/test/scala/ch/datascience/dbeventlog/commands/EventLogAddSpec.scala
db-event-log/src/test/scala/ch/datascience/dbeventlog/commands/EventLogFetchImplSpec.scala
db-event-log/src/test/scala/ch/datascience/dbeventlog/commands/EventLogMarkDoneSpec.scala
db-event-log/src/test/scala/ch/datascience/dbeventlog/commands/EventLogMarkNewSpec.scala
db-event-log/src/test/scala/ch/datascience/dbeventlog/commands/EventLogProcessingStatusSpec.scala
db-event-log/src/test/scala/ch/datascience/dbeventlog/commands/EventLogReSchedulerSpec.scala
db-event-log/src/test/scala/ch/datascience/dbeventlog/commands/InMemoryEventLogDbSpec.scala
db-event-log/src/test/scala/ch/datascience/dbeventlog/init/BatchDateAdderSpec.scala
db-event-log/src/test/scala/ch/datascience/dbeventlog/init/EventLogDbInitializerSpec.scala
graph-commons/src/main/resources/application.conf
graph-commons/src/main/scala/ch/datascience/graph/model/events.scala
graph-commons/src/test/scala/ch/datascience/graph/model/EventsGenerators.scala
graph-commons/src/test/scala/ch/datascience/graph/model/eventsSpec.scala
helm-chart/renku-graph/Chart.yaml
version.sbt
webhook-service/src/main/scala/ch/datascience/webhookservice/eventprocessing/startcommit/CommitEventsSourceBuilder.scala
webhook-service/src/main/scala/ch/datascience/webhookservice/eventprocessing/startcommit/CommitToEventLog.scala
webhook-service/src/test/scala/ch/datascience/webhookservice/eventprocessing/startcommit/CommitEventsSourceBuilderSpec.scala
webhook-service/src/test/scala/ch/datascience/webhookservice/eventprocessing/startcommit/CommitToEventLogSpec.scala

Status endpoint bug

---

db-event-log/src/main/scala/ch/datascience/dbeventlog/commands/EventLogFetch.scala
db-event-log/src/main/scala/ch/datascience/dbeventlog/commands/EventLogMarkFailed.scala
db-event-log/src/test/scala/ch/datascience/dbeventlog/commands/EventLogFetchImplSpec.scala
db-event-log/src/test/scala/ch/datascience/dbeventlog/commands/ExecutionDateCalculatorSpec.scala
helm-chart/renku-graph/values.yaml
triples-generator/src/main/scala/ch/datascience/triplesgenerator/eventprocessing/triplesgeneration/renkulog/Commands.scala
triples-generator/src/test/scala/ch/datascience/triplesgenerator/eventprocessing/triplesgeneration/renkulog/GitSpec.scala
triples-generator/src/test/scala/ch/datascience/triplesgenerator/eventprocessing/triplesgeneration/renkulog/RenkuLogTriplesGeneratorSpec.scala

Git clone does not clasify recoverable errors correctly

---

db-event-log/src/main/scala/ch/datascience/dbeventlog/commands/EventLogFetch.scala

closes #278
Image for testing:
{'repository': 'jachro/triples-generator', 'tag': '5fb3d88a'}

fix: so all the projects in the queue have the same chances to be picked

---

helm-chart/renku-graph/Chart.yaml
triples-generator/src/main/scala/ch/datascience/triplesgenerator/eventprocessing/triplescuration/package.scala
triples-generator/src/main/scala/ch/datascience/triplesgenerator/eventprocessing/triplescuration/persondetails/PersonDetailsUpdater.scala
triples-generator/src/main/scala/ch/datascience/triplesgenerator/eventprocessing/triplescuration/persondetails/UpdatesCreator.scala
triples-generator/src/test/scala/ch/datascience/triplesgenerator/eventprocessing/triplescuration/persondetails/PersonDetailsUpdaterSpec.scala
triples-generator/src/test/scala/ch/datascience/triplesgenerator/eventprocessing/triplescuration/persondetails/UpdatesCreatorSpec.scala
version.sbt

Triples generation fail to insert person data

---

helm-chart/renku-graph/Chart.yaml
version.sbt
webhook-service/src/main/scala/ch/datascience/webhookservice/eventprocessing/ProcessingStatusEndpoint.scala
webhook-service/src/main/scala/ch/datascience/webhookservice/eventprocessing/ProcessingStatusFetcher.scala
webhook-service/src/test/scala/ch/datascience/webhookservice/eventprocessing/IOProcessingStatusFetcherSpec.scala
webhook-service/src/test/scala/ch/datascience/webhookservice/eventprocessing/ProcessingStatusEndpointSpec.scala
webhook-service/src/test/scala/ch/datascience/webhookservice/eventprocessing/ProcessingStatusGenerator.scala

fix: Project event status returning 500

---

helm-chart/renku-graph/charts/jena/templates/deployment.yaml
helm-chart/renku-graph/charts/jena/templates/docker-entrypoint.yaml
helm-chart/renku-graph/charts/jena/templates/fuseki-server.yaml
helm-chart/renku-graph/charts/jena/templates/lucene-config.yaml
helm-chart/renku-graph/templates/event-log-deployment.yaml
helm-chart/renku-graph/templates/knowledge-graph-deployment.yaml
helm-chart/renku-graph/templates/token-repository-deployment.yaml
helm-chart/renku-graph/templates/triples-generator-deployment.yaml
helm-chart/renku-graph/templates/webhook-service-deployment.yaml

Fix bugs in templates that led to validation problems and ignored resource limits.

Fix several bugs in the helm templates

---

acceptance-tests/src/test/scala/ch/datascience/graph/acceptancetests/flows/RdfStoreProvisioning.scala
acceptance-tests/src/test/scala/ch/datascience/graph/acceptancetests/knowledgegraph/DatasetsResourcesSpec.scala
acceptance-tests/src/test/scala/ch/datascience/graph/acceptancetests/knowledgegraph/ProjectsResourcesSpec.scala
acceptance-tests/src/test/scala/ch/datascience/graph/acceptancetests/stubs/RemoteTriplesGenerator.scala
graph-commons/src/test/scala/ch/datascience/rdfstore/entities/Project.scala
graph-commons/src/test/scala/ch/datascience/rdfstore/entities/bundles.scala
knowledge-graph/README.md
knowledge-graph/src/main/scala/ch/datascience/knowledgegraph/projects/model.scala
knowledge-graph/src/main/scala/ch/datascience/knowledgegraph/projects/rest/KGProjectFinder.scala
knowledge-graph/src/main/scala/ch/datascience/knowledgegraph/projects/rest/ProjectEndpoint.scala
knowledge-graph/src/main/scala/ch/datascience/knowledgegraph/projects/rest/ProjectFinder.scala
knowledge-graph/src/test/scala/ch/datascience/knowledgegraph/projects/ProjectsGenerators.scala
knowledge-graph/src/test/scala/ch/datascience/knowledgegraph/projects/rest/IOKGProjectFinderSpec.scala
knowledge-graph/src/test/scala/ch/datascience/knowledgegraph/projects/rest/ProjectEndpointSpec.scala
knowledge-graph/src/test/scala/ch/datascience/knowledgegraph/projects/rest/ProjectFinderSpec.scala
triples-generator/src/test/scala/ch/datascience/triplesgenerator/eventprocessing/triplescuration/forks/ProjectPropertiesRemoverSpec.scala
triples-generator/src/test/scala/ch/datascience/triplesgenerator/eventprocessing/triplescuration/forks/package.scala

feature: add version to project details API endpoint

---

helm-chart/renku-graph/Chart.yaml
helm-chart/renku-graph/templates/triples-generator-deployment.yaml
triples-generator/Dockerfile
version.sbt

Renku version check disabled on TG instance

---

helm-chart/renku-graph/Chart.yaml
helm-chart/renku-graph/templates/event-log-deployment.yaml
knowledge-graph/src/main/scala/ch/datascience/knowledgegraph/metrics/StatsFinder.scala
knowledge-graph/src/main/scala/ch/datascience/knowledgegraph/metrics/package.scala
knowledge-graph/src/test/scala/ch/datascience/knowledgegraph/metrics/StatsFinderSpec.scala
version.sbt

Flaky tests

---

event-log/src/main/resources/application.conf
event-log/src/main/scala/io/renku/eventlog/subscriptions/EventsDispatcher.scala
event-log/src/main/scala/io/renku/eventlog/subscriptions/Subscriptions.scala
event-log/src/main/scala/io/renku/eventlog/subscriptions/SubscriptionsEndpoint.scala
event-log/src/test/scala/io/renku/eventlog/subscriptions/EventsDispatcherSpec.scala
event-log/src/test/scala/io/renku/eventlog/subscriptions/SubscriptionsSpec.scala
helm-chart/renku-graph/Chart.yaml
triples-generator/src/main/scala/ch/datascience/triplesgenerator/subscriptions/Subscriber.scala
version.sbt

Event log restarting

---

event-log/src/main/resources/logback.xml
event-log/src/test/scala/io/renku/eventlog/subscriptions/SubscriptionsSpec.scala
helm-chart/renku-graph/Chart.yaml
knowledge-graph/src/main/resources/logback.xml
token-repository/src/main/resources/logback.xml
triples-generator/src/main/resources/logback.xml
version.sbt
webhook-service/src/main/resources/logback.xml

fix: change TG sentry reporting from WARN => ERROR - closes 379

---

helm-chart/renku-graph/Chart.yaml
helm-chart/renku-graph/values.yaml
version.sbt

    enhancement: update memory settings in dev across services

---

graph-commons/src/main/scala/ch/datascience/graph/model/datasets.scala
graph-commons/src/test/scala/ch/datascience/graph/model/GraphModelGenerators.scala
graph-commons/src/test/scala/ch/datascience/graph/model/datasetsSpec.scala
graph-commons/src/test/scala/ch/datascience/rdfstore/entities/package.scala
helm-chart/renku-graph/Chart.yaml
knowledge-graph/src/test/scala/ch/datascience/knowledgegraph/datasets/rest/package.scala
triples-generator/src/main/scala/ch/datascience/triplesgenerator/eventprocessing/triplescuration/datasets/DataSetInfoFinder.scala
triples-generator/src/main/scala/ch/datascience/triplesgenerator/eventprocessing/triplescuration/datasets/KGDatasetInfoFinder.scala
triples-generator/src/main/scala/ch/datascience/triplesgenerator/eventprocessing/triplescuration/datasets/TopmostDataFinder.scala
triples-generator/src/test/scala/ch/datascience/triplesgenerator/eventprocessing/triplescuration/datasets/DataSetInfoFinderSpec.scala
triples-generator/src/test/scala/ch/datascience/triplesgenerator/eventprocessing/triplescuration/datasets/KGDatasetInfoFinderSpec.scala
triples-generator/src/test/scala/ch/datascience/triplesgenerator/eventprocessing/triplescuration/datasets/TopmostDataFinderSpec.scala
version.sbt

SameAs to be always read/write to @id in json-ld

---

graph-commons/src/main/scala/ch/datascience/graph/model/datasets.scala
graph-commons/src/test/scala/ch/datascience/graph/model/GraphModelGenerators.scala
graph-commons/src/test/scala/ch/datascience/graph/model/datasetsSpec.scala
graph-commons/src/test/scala/ch/datascience/rdfstore/entities/package.scala
helm-chart/renku-graph/Chart.yaml
triples-generator/src/main/scala/ch/datascience/triplesgenerator/eventprocessing/triplescuration/datasets/DataSetInfoFinder.scala
triples-generator/src/main/scala/ch/datascience/triplesgenerator/eventprocessing/triplescuration/datasets/KGDatasetInfoFinder.scala
triples-generator/src/main/scala/ch/datascience/triplesgenerator/eventprocessing/triplescuration/datasets/TopmostDataFinder.scala
triples-generator/src/main/scala/ch/datascience/triplesgenerator/eventprocessing/triplescuration/package.scala
triples-generator/src/test/scala/ch/datascience/triplesgenerator/eventprocessing/triplescuration/datasets/DataSetInfoFinderSpec.scala
triples-generator/src/test/scala/ch/datascience/triplesgenerator/eventprocessing/triplescuration/datasets/KGDatasetInfoFinderSpec.scala
triples-generator/src/test/scala/ch/datascience/triplesgenerator/eventprocessing/triplescuration/datasets/TopmostDataFinderSpec.scala
version.sbt

TG to work with flattened payloads

---

event-log/src/main/scala/io/renku/eventlog/subscriptions/EventsDispatcher.scala
event-log/src/main/scala/io/renku/eventlog/subscriptions/Subscriptions.scala
event-log/src/test/scala/io/renku/eventlog/subscriptions/EventsDispatcherSpec.scala
event-log/src/test/scala/io/renku/eventlog/subscriptions/SubscriptionsSpec.scala
helm-chart/renku-graph/Chart.yaml
version.sbt

Events dispatcher to act on subscriber become available

---

helm-chart/renku-graph/Chart.yaml
triples-generator/Dockerfile
triples-generator/src/main/scala/ch/datascience/triplesgenerator/eventprocessing/triplesgeneration/renkulog/Commands.scala
version.sbt

TG to generate log for a single commit without migration commits

---

graph-commons/src/main/scala/ch/datascience/graph/model/datasets.scala
graph-commons/src/test/scala/ch/datascience/graph/model/GraphModelGenerators.scala
graph-commons/src/test/scala/ch/datascience/graph/model/datasetsSpec.scala
graph-commons/src/test/scala/ch/datascience/rdfstore/entities/DataSet.scala
graph-commons/src/test/scala/ch/datascience/rdfstore/entities/bundles.scala
helm-chart/renku-graph/Chart.yaml
knowledge-graph/src/main/scala/ch/datascience/knowledgegraph/datasets/rest/BaseDetailsFinder.scala
knowledge-graph/src/main/scala/ch/datascience/knowledgegraph/datasets/rest/DatasetsFinder.scala
knowledge-graph/src/main/scala/ch/datascience/knowledgegraph/datasets/rest/ProjectDatasetsFinder.scala
knowledge-graph/src/test/scala/ch/datascience/knowledgegraph/datasets/rest/IODatasetFinderSpec.scala
knowledge-graph/src/test/scala/ch/datascience/knowledgegraph/datasets/rest/IODatasetsFinderSpec.scala
knowledge-graph/src/test/scala/ch/datascience/knowledgegraph/datasets/rest/IOProjectDatasetsFinderSpec.scala
knowledge-graph/src/test/scala/ch/datascience/knowledgegraph/datasets/rest/package.scala
triples-generator/src/main/scala/ch/datascience/triplesgenerator/eventprocessing/triplescuration/datasets/DataSetInfoFinder.scala
triples-generator/src/main/scala/ch/datascience/triplesgenerator/eventprocessing/triplescuration/datasets/DescendantsUpdater.scala
triples-generator/src/main/scala/ch/datascience/triplesgenerator/eventprocessing/triplescuration/datasets/KGDatasetInfoFinder.scala
triples-generator/src/main/scala/ch/datascience/triplesgenerator/eventprocessing/triplescuration/datasets/TopmostDataFinder.scala
triples-generator/src/main/scala/ch/datascience/triplesgenerator/eventprocessing/triplescuration/datasets/TriplesUpdater.scala
triples-generator/src/test/scala/ch/datascience/triplesgenerator/eventprocessing/triplescuration/datasets/DataSetInfoEnricherSpec.scala
triples-generator/src/test/scala/ch/datascience/triplesgenerator/eventprocessing/triplescuration/datasets/DescendantsUpdaterSpec.scala
triples-generator/src/test/scala/ch/datascience/triplesgenerator/eventprocessing/triplescuration/datasets/KGDatasetInfoFinderSpec.scala
triples-generator/src/test/scala/ch/datascience/triplesgenerator/eventprocessing/triplescuration/datasets/TopmostDataFinderSpec.scala
triples-generator/src/test/scala/ch/datascience/triplesgenerator/eventprocessing/triplescuration/datasets/TriplesUpdaterSpec.scala
version.sbt

fix: fix queries and tests for derivedFrom structure in KG

---

.scalafmt.conf
graph-commons/src/main/scala/ch/datascience/graph/Schemas.scala
graph-commons/src/main/scala/ch/datascience/rdfstore/SparqlQuery.scala
graph-commons/src/test/scala/ch/datascience/rdfstore/SparqlQuerySpec.scala
helm-chart/renku-graph/Chart.yaml
json-ld/src/main/scala/io/renku/jsonld/Schema.scala
json-ld/src/test/scala/io/renku/jsonld/SchemaSpec.scala
knowledge-graph/src/main/scala/ch/datascience/knowledgegraph/metrics/KGMetrics.scala
knowledge-graph/src/main/scala/ch/datascience/knowledgegraph/metrics/StatsFinder.scala
knowledge-graph/src/main/scala/ch/datascience/knowledgegraph/metrics/package.scala
knowledge-graph/src/test/scala/ch/datascience/knowledgegraph/MicroserviceRunnerSpec.scala
knowledge-graph/src/test/scala/ch/datascience/knowledgegraph/metrics/KGMetricsSpec.scala
knowledge-graph/src/test/scala/ch/datascience/knowledgegraph/metrics/MetricsGenerators.scala
knowledge-graph/src/test/scala/ch/datascience/knowledgegraph/metrics/StatsFinderSpec.scala
version.sbt

New KG metrics

---

helm-chart/renku-graph/Chart.yaml
helm-chart/renku-graph/values.yaml
triples-generator/Dockerfile
version.sbt

This PR pins Renku Cli v0.11.4 and adjusts TG memory requirements.

Renku Cli upgrade

---

helm-chart/renku-graph/Chart.yaml
triples-generator/src/main/scala/ch/datascience/triplesgenerator/eventprocessing/triplesgeneration/renkulog/Commands.scala
triples-generator/src/test/scala/ch/datascience/triplesgenerator/eventprocessing/triplesgeneration/renkulog/GitSpec.scala
version.sbt

fix: classify GitLab 502 error & host resolution error as recoverable

---

helm-chart/renku-graph/Chart.yaml
helm-chart/renku-graph/values.yaml
version.sbt

fix: TG memory limits raised up

---

event-log/src/test/scala/io/renku/eventlog/subscriptions/SubscribersRegistrySpec.scala

increase patience in subscriber registry spec

---

event-log/src/main/scala/io/renku/eventlog/subscriptions/EventFetcher.scala
event-log/src/test/scala/io/renku/eventlog/subscriptions/EventFetcherSpec.scala
helm-chart/renku-graph/Chart.yaml
version.sbt
webhook-service/src/test/scala/ch/datascience/webhookservice/eventprocessing/IOProcessingStatusFetcherSpec.scala

This PR fixes an issue in selecting the next event for dispatching

Dispatcher randomness bug

---

event-log/src/main/scala/io/renku/eventlog/init/BatchDateAdder.scala
helm-chart/renku-graph/Chart.yaml
helm-chart/renku-graph/values.yaml
version.sbt

This PR fixes a bug in the DB initialisation process responsible for adding the `batch_date` column.

Batch date column migration bug

---

build.sbt
event-log/src/test/scala/io/renku/eventlog/subscriptions/SubscribersRegistrySpec.scala
graph-commons/src/test/scala/ch/datascience/generators/Generators.scala
helm-chart/renku-graph/Chart.yaml
knowledge-graph/src/test/scala/ch/datascience/knowledgegraph/datasets/rest/package.scala
version.sbt

fix for the release process

---

acceptance-tests/src/test/resources/application.conf
acceptance-tests/src/test/scala/ch/datascience/graph/acceptancetests/db/EventLog.scala
acceptance-tests/src/test/scala/ch/datascience/graph/acceptancetests/db/TokenRepository.scala
acceptance-tests/src/test/scala/ch/datascience/graph/acceptancetests/tooling/GraphServices.scala
acceptance-tests/src/test/scala/ch/datascience/graph/acceptancetests/tooling/ServicesRunner.scala
event-log/build.sbt
event-log/src/main/scala/io/renku/eventlog/Microservice.scala
event-log/src/main/scala/io/renku/eventlog/init/DbInitializer.scala
event-log/src/main/scala/io/renku/eventlog/subscriptions/EventFetcher.scala
event-log/src/test/scala/io/renku/eventlog/InMemoryEventLogDb.scala
event-log/src/test/scala/io/renku/eventlog/init/DbInitializerSpec.scala
event-log/src/test/scala/io/renku/eventlog/metrics/StatsFinderSpec.scala
event-log/src/test/scala/io/renku/eventlog/subscriptions/EventFetcherSpec.scala
graph-commons/build.sbt
graph-commons/src/main/scala/ch/datascience/db/DBConfigProvider.scala
graph-commons/src/test/scala/ch/datascience/db/DBConfigProviderSpec.scala
graph-commons/src/test/scala/ch/datascience/generators/Generators.scala
helm-chart/renku-graph/Chart.yaml
knowledge-graph/src/test/scala/ch/datascience/knowledgegraph/datasets/rest/IODatasetFinderSpec.scala
knowledge-graph/src/test/scala/ch/datascience/knowledgegraph/datasets/rest/package.scala
token-repository/build.sbt
token-repository/src/main/scala/ch/datascience/tokenrepository/Microservice.scala
token-repository/src/main/scala/ch/datascience/tokenrepository/repository/ProjectsTokensDbConfigProvider.scala
token-repository/src/test/scala/ch/datascience/tokenrepository/repository/InMemoryProjectsTokensDb.scala
version.sbt

fix: slow pop event - projects query

---

event-log/src/main/scala/io/renku/eventlog/init/DbInitializer.scala
event-log/src/main/scala/io/renku/eventlog/init/LatestEventDatesViewCreator.scala
event-log/src/main/scala/io/renku/eventlog/metrics/StatsFinder.scala
event-log/src/main/scala/io/renku/eventlog/metrics/WaitingEventsGauge.scala
event-log/src/main/scala/io/renku/eventlog/subscriptions/EventFetcher.scala
event-log/src/main/scala/io/renku/eventlog/subscriptions/EventsDispatcher.scala
event-log/src/test/scala/io/renku/eventlog/InMemoryEventLogDb.scala
event-log/src/test/scala/io/renku/eventlog/LatestEventDatesViewPresence.scala
event-log/src/test/scala/io/renku/eventlog/init/DbInitSpec.scala
event-log/src/test/scala/io/renku/eventlog/init/DbInitializerSpec.scala
event-log/src/test/scala/io/renku/eventlog/init/LatestEventDatesViewCreatorSpec.scala
event-log/src/test/scala/io/renku/eventlog/metrics/StatsFinderSpec.scala
event-log/src/test/scala/io/renku/eventlog/metrics/UnderProcessingGaugeSpec.scala
event-log/src/test/scala/io/renku/eventlog/metrics/WaitingEventsGaugeSpec.scala
event-log/src/test/scala/io/renku/eventlog/subscriptions/EventFetcherSpec.scala

Top priority queued events refactored

---

event-log/src/main/scala/io/renku/eventlog/subscriptions/SubscribersRegistry.scala
helm-chart/renku-graph/Chart.yaml
version.sbt

fix: removing recursive call for event log loop subscribers check

---

event-log/src/main/scala/io/renku/eventlog/metrics/StatsFinder.scala
event-log/src/main/scala/io/renku/eventlog/subscriptions/EventFetcher.scala
helm-chart/renku-graph/Chart.yaml
version.sbt

It looked there was some room for improvement the slow queries performance. This PR tries to do some saving on ordering.

View queries speed up

---

event-log/src/main/scala/io/renku/eventlog/subscriptions/EventsDispatcher.scala
event-log/src/test/scala/io/renku/eventlog/subscriptions/EventsDispatcherSpec.scala
helm-chart/renku-graph/Chart.yaml
triples-generator/src/test/scala/ch/datascience/triplesgenerator/subscriptions/SubscriberSpec.scala
version.sbt

tg and el stop working at some circumstances

---

.github/workflows/test-publish.yml

chore: set env for whole GitHub Action workflow - closes #472

---

event-log/src/main/scala/io/renku/eventlog/subscriptions/ProjectPrioritisation.scala
event-log/src/test/scala/io/renku/eventlog/subscriptions/ProjectPrioritisationSpec.scala
helm-chart/renku-graph/Chart.yaml
version.sbt

This PR prevents from one project to dominate provisioning

Events prioritisation changes

---

graph-commons/src/main/scala/ch/datascience/http/client/IORestClient.scala
graph-commons/src/test/scala/ch/datascience/http/client/IORestClientSpec.scala
helm-chart/renku-graph/Chart.yaml
triples-generator/src/main/scala/ch/datascience/triplesgenerator/eventprocessing/triplesuploading/TriplesUploader.scala
triples-generator/src/main/scala/ch/datascience/triplesgenerator/eventprocessing/triplesuploading/Uploader.scala
triples-generator/src/test/scala/ch/datascience/triplesgenerator/eventprocessing/triplesuploading/TriplesUploaderSpec.scala
version.sbt

Extending http timeout for triples uploading

---

.bsp/sbt.json
.gitignore
acceptance-tests/src/test/scala/ch/datascience/graph/acceptancetests/db/EventLog.scala
acceptance-tests/src/test/scala/ch/datascience/graph/acceptancetests/db/TokenRepository.scala
build.sbt
event-log/src/test/scala/io/renku/eventlog/InMemoryEventLogDb.scala
graph-commons/build.sbt
graph-commons/src/main/scala/ch/datascience/config/sentry/SentryInitializer.scala
graph-commons/src/main/scala/ch/datascience/http/rest/Links.scala
graph-commons/src/main/scala/ch/datascience/tinytypes/TinyType.scala
helm-chart/renku-graph/Chart.yaml
json-ld/build.sbt
knowledge-graph/build.sbt
knowledge-graph/src/main/scala/ch/datascience/knowledgegraph/datasets/rest/BaseDetailsFinder.scala
knowledge-graph/src/main/scala/ch/datascience/knowledgegraph/lineage/EdgesFinder.scala
knowledge-graph/src/main/scala/ch/datascience/knowledgegraph/lineage/LineageDataFinder.scala
knowledge-graph/src/main/scala/ch/datascience/knowledgegraph/lineage/NodesDetailsFinder.scala
knowledge-graph/src/test/scala/ch/datascience/knowledgegraph/datasets/rest/IODatasetsFinderSpec.scala
knowledge-graph/src/test/scala/ch/datascience/knowledgegraph/datasets/rest/package.scala
project/build.properties
project/plugins.sbt
token-repository/src/test/scala/ch/datascience/tokenrepository/repository/InMemoryProjectsTokensDb.scala
triples-generator/build.sbt
triples-generator/src/main/scala/ch/datascience/triplesgenerator/eventprocessing/triplescuration/persondetails/PersonDetailsUpdater.scala
version.sbt
webhook-service/src/main/scala/ch/datascience/webhookservice/missedevents/EventsSynchronizationScheduler.scala
webhook-service/src/test/scala/ch/datascience/webhookservice/missedevents/EventsSynchronizationSchedulerSpec.scala
webhook-service/src/test/scala/ch/datascience/webhookservice/missedevents/interpreters.scala

387 update service libs

---

dashboards/event-log.json
version.sbt

Fixing the metrics names on the Event Log dashboard

fix: Event Log dashboard

---

acceptance-tests/src/test/scala/ch/datascience/graph/acceptancetests/flows/RdfStoreProvisioning.scala
acceptance-tests/src/test/scala/ch/datascience/graph/acceptancetests/knowledgegraph/DatasetsResourcesSpec.scala
acceptance-tests/src/test/scala/ch/datascience/graph/acceptancetests/knowledgegraph/ProjectsResourcesSpec.scala
acceptance-tests/src/test/scala/ch/datascience/graph/acceptancetests/stubs/GitLab.scala
acceptance-tests/src/test/scala/ch/datascience/graph/acceptancetests/tooling/ModelImplicits.scala
graph-commons/src/main/scala/ch/datascience/graph/config/RenkuBaseUrl.scala
graph-commons/src/test/scala/ch/datascience/rdfstore/entities/Person.scala
triples-generator/src/main/scala/ch/datascience/triplesgenerator/eventprocessing/CommitEventProcessor.scala
triples-generator/src/main/scala/ch/datascience/triplesgenerator/eventprocessing/triplescuration/forks/GitLabInfoFinder.scala
triples-generator/src/main/scala/ch/datascience/triplesgenerator/eventprocessing/triplescuration/forks/KGInfoFinder.scala
triples-generator/src/main/scala/ch/datascience/triplesgenerator/eventprocessing/triplescuration/forks/PayloadTransformer.scala
triples-generator/src/main/scala/ch/datascience/triplesgenerator/eventprocessing/triplescuration/forks/UpdatesCreator.scala
triples-generator/src/main/scala/ch/datascience/triplesgenerator/eventprocessing/triplescuration/forks/UpdatesQueryCreator.scala
triples-generator/src/main/scala/ch/datascience/triplesgenerator/eventprocessing/triplescuration/forks/model.scala
triples-generator/src/main/scala/ch/datascience/triplesgenerator/eventprocessing/triplescuration/persondetails/PersonExtractor.scala
triples-generator/src/test/scala/ch/datascience/triplesgenerator/eventprocessing/triplescuration/forks/GitLabInfoFinderSpec.scala
triples-generator/src/test/scala/ch/datascience/triplesgenerator/eventprocessing/triplescuration/forks/KGInfoFinderSpec.scala
triples-generator/src/test/scala/ch/datascience/triplesgenerator/eventprocessing/triplescuration/forks/UpdatesCreatorSpec.scala
triples-generator/src/test/scala/ch/datascience/triplesgenerator/eventprocessing/triplescuration/forks/UpdatesQueryCreatorSpec.scala
triples-generator/src/test/scala/ch/datascience/triplesgenerator/eventprocessing/triplescuration/forks/package.scala
triples-generator/src/test/scala/ch/datascience/triplesgenerator/eventprocessing/triplescuration/persondetails/PersonExtractorSpec.scala
version.sbt

feat: use GitLabId to find project creator

---

graph-commons/src/main/scala/ch/datascience/config/certificates/Certificate.scala
graph-commons/src/main/scala/ch/datascience/config/certificates/CertificateLoader.scala
graph-commons/src/test/scala/ch/datascience/config/certificates/CertificateLoaderSpec.scala
graph-commons/src/test/scala/ch/datascience/generators/CommonGraphGenerators.scala
triples-generator/src/main/scala/ch/datascience/triplesgenerator/Microservice.scala
triples-generator/src/main/scala/ch/datascience/triplesgenerator/config/certificates/CertificateSaver.scala
triples-generator/src/main/scala/ch/datascience/triplesgenerator/config/certificates/GitCertificateInstaller.scala
triples-generator/src/main/scala/ch/datascience/triplesgenerator/config/certificates/GitConfigModifier.scala
triples-generator/src/main/scala/ch/datascience/triplesgenerator/eventprocessing/triplesgeneration/renkulog/Commands.scala
triples-generator/src/test/scala/ch/datascience/triplesgenerator/MicroserviceRunnerSpec.scala
triples-generator/src/test/scala/ch/datascience/triplesgenerator/config/certificates/CertificateSaverSpec.scala
triples-generator/src/test/scala/ch/datascience/triplesgenerator/config/certificates/GitCertificateInstallerSpec.scala
version.sbt

git clone on TG to use certificate if given

---

dashboards/event-log.json
event-log/src/main/scala/io/renku/eventlog/init/EventPayloadSchemaVersionAdder.scala
event-log/src/main/scala/io/renku/eventlog/model.scala
event-log/src/test/scala/io/renku/eventlog/init/EventPayloadSchemaVersionAdderSpec.scala
event-log/src/test/scala/io/renku/eventlog/modelSpec.scala
graph-commons/src/main/scala/ch/datascience/graph/model/events.scala
graph-commons/src/main/scala/ch/datascience/tinytypes/constraints/BoundedInstant.scala
graph-commons/src/test/scala/ch/datascience/generators/Generators.scala
graph-commons/src/test/scala/ch/datascience/graph/model/eventsSpec.scala
graph-commons/src/test/scala/ch/datascience/tinytypes/constraints/BoundedInstantSpec.scala
triples-generator/src/test/scala/ch/datascience/triplesgenerator/eventprocessing/EventsProcessingRunnerSpec.scala
version.sbt

fix: CommittedDate and EventPayloadSchemaVersionAdder

---

event-log/src/test/scala/io/renku/eventlog/init/EventStatusRenamerImplSpec.scala
token-repository/src/main/scala/ch/datascience/tokenrepository/Microservice.scala
token-repository/src/main/scala/ch/datascience/tokenrepository/repository/association/AssociateTokenEndpoint.scala
token-repository/src/main/scala/ch/datascience/tokenrepository/repository/association/AssociationPersister.scala
token-repository/src/main/scala/ch/datascience/tokenrepository/repository/association/TokenAssociator.scala
token-repository/src/main/scala/ch/datascience/tokenrepository/repository/init/DbInitializer.scala
token-repository/src/main/scala/ch/datascience/tokenrepository/repository/init/DuplicateProjectsRemover.scala
token-repository/src/main/scala/ch/datascience/tokenrepository/repository/metrics/QueriesExecutionTimes.scala
token-repository/src/test/scala/ch/datascience/tokenrepository/repository/association/AssociationPersisterSpec.scala
token-repository/src/test/scala/ch/datascience/tokenrepository/repository/association/interpreters.scala
token-repository/src/test/scala/ch/datascience/tokenrepository/repository/init/DbInitializerSpec.scala
token-repository/src/test/scala/ch/datascience/tokenrepository/repository/init/DuplicateProjectsRemoverSpec.scala
token-repository/src/test/scala/ch/datascience/tokenrepository/repository/init/interpreters.scala
version.sbt

token update when project re-created

---

knowledge-graph/src/main/scala/ch/datascience/knowledgegraph/projects/rest/ProjectFinder.scala
triples-generator/src/main/scala/ch/datascience/triplesgenerator/eventprocessing/CommitEventProcessor.scala
triples-generator/src/test/scala/ch/datascience/triplesgenerator/eventprocessing/CommitEventProcessorSpec.scala
version.sbt
webhook-service/src/main/scala/ch/datascience/webhookservice/eventprocessing/startcommit/CommitToEventLog.scala
webhook-service/src/main/scala/ch/datascience/webhookservice/missedevents/LatestEventsFetcher.scala
webhook-service/src/main/scala/ch/datascience/webhookservice/missedevents/MissedEventsLoader.scala
webhook-service/src/test/scala/ch/datascience/webhookservice/eventprocessing/startcommit/CommitToEventLogSpec.scala
webhook-service/src/test/scala/ch/datascience/webhookservice/missedevents/IOLatestEventsFetcherSpec.scala
webhook-service/src/test/scala/ch/datascience/webhookservice/missedevents/IOMissedEventsLoaderSpec.scala
webhook-service/src/test/scala/ch/datascience/webhookservice/missedevents/package.scala

Graph services to fetch project access token by path

---

dashboards/sql-execution-times.json
graph-commons/src/test/scala/ch/datascience/metrics/TestLabeledHistogram.scala
token-repository/src/main/scala/ch/datascience/tokenrepository/Microservice.scala
token-repository/src/main/scala/ch/datascience/tokenrepository/repository/association/TokenAssociator.scala
token-repository/src/main/scala/ch/datascience/tokenrepository/repository/deletion/DeleteTokenEndpoint.scala
token-repository/src/main/scala/ch/datascience/tokenrepository/repository/deletion/TokenRemover.scala
token-repository/src/main/scala/ch/datascience/tokenrepository/repository/fetching/FetchTokenEndpoint.scala
token-repository/src/main/scala/ch/datascience/tokenrepository/repository/fetching/PersistedTokensFinder.scala
token-repository/src/main/scala/ch/datascience/tokenrepository/repository/fetching/TokenFinder.scala
token-repository/src/main/scala/ch/datascience/tokenrepository/repository/init/DbInitializer.scala
token-repository/src/main/scala/ch/datascience/tokenrepository/repository/init/ProjectPathAdder.scala
token-repository/src/test/scala/ch/datascience/tokenrepository/repository/association/AssociationPersisterSpec.scala
token-repository/src/test/scala/ch/datascience/tokenrepository/repository/deletion/TokenRemoverSpec.scala
token-repository/src/test/scala/ch/datascience/tokenrepository/repository/deletion/interpreters.scala
token-repository/src/test/scala/ch/datascience/tokenrepository/repository/fetching/PersistedTokensFinderSpec.scala
token-repository/src/test/scala/ch/datascience/tokenrepository/repository/fetching/interpreters.scala
token-repository/src/test/scala/ch/datascience/tokenrepository/repository/init/ProjectPathAdderSpec.scala
version.sbt

token-repository to measure SQLs execution times

---

event-log/src/main/resources/application.conf
graph-commons/src/main/scala/ch/datascience/config/sentry/SentryConfig.scala
graph-commons/src/main/scala/ch/datascience/config/sentry/SentryInitializer.scala
graph-commons/src/test/scala/ch/datascience/config/sentry/SentryConfigSpec.scala
graph-commons/src/test/scala/ch/datascience/config/sentry/SentryInitializerSpec.scala
graph-commons/src/test/scala/ch/datascience/generators/CommonGraphGenerators.scala
knowledge-graph/src/main/resources/application.conf
token-repository/src/main/resources/application.conf
triples-generator/src/main/resources/application.conf
version.sbt
webhook-service/src/main/resources/application.conf

chore: added sentry stack trace package

---

event-log/README.md
event-log/src/main/scala/io/renku/eventlog/init/DbInitializer.scala
event-log/src/main/scala/io/renku/eventlog/init/SubscriptionCategorySyncTimeTableCreator.scala
event-log/src/test/scala/io/renku/eventlog/init/DbInitSpec.scala
event-log/src/test/scala/io/renku/eventlog/init/DbInitializerSpec.scala
event-log/src/test/scala/io/renku/eventlog/init/SubscriptionCategorySyncTimeTableCreatorSpec.scala
version.sbt

feat: new DB table 'subscription_category_sync_time' - implements #433

---

triples-generator/src/main/scala/ch/datascience/triplesgenerator/events/categories/awaitinggeneration/CommitEventProcessor.scala
triples-generator/src/main/scala/ch/datascience/triplesgenerator/events/categories/membersync/MembersSynchronizer.scala
triples-generator/src/test/scala/ch/datascience/triplesgenerator/events/categories/awaitinggeneration/CommitEventProcessorSpec.scala
triples-generator/src/test/scala/ch/datascience/triplesgenerator/events/categories/membersync/MembersSynchronizerSpec.scala
version.sbt

* Added category name context to the EventsProcessor logs
* Added execution time and stats to the MembersSynchronizer logs

More informative log statements

---

acceptance-tests/build.sbt
acceptance-tests/project/build.properties
event-log/project/build.properties
event-log/src/main/scala/io/renku/eventlog/Microservice.scala
graph-commons/build.sbt
graph-commons/project/build.properties
json-ld/build.sbt
knowledge-graph/build.sbt
knowledge-graph/project/build.properties
knowledge-graph/src/main/scala/ch/datascience/knowledgegraph/Microservice.scala
project/build.properties
project/plugins.sbt
token-repository/project/build.properties
triples-generator/project/build.properties
triples-generator/src/main/scala/ch/datascience/triplesgenerator/Microservice.scala
version.sbt
webhook-service/project/build.properties
webhook-service/src/main/scala/ch/datascience/webhookservice/Microservice.scala

387 update project libs 2

---

event-log/src/main/scala/io/renku/eventlog/subscriptions/Subscribers.scala
event-log/src/main/scala/io/renku/eventlog/subscriptions/SubscribersRegistry.scala
event-log/src/main/scala/io/renku/eventlog/subscriptions/SubscriptionCategory.scala
event-log/src/main/scala/io/renku/eventlog/subscriptions/SubscriptionRequestDeserializer.scala
event-log/src/main/scala/io/renku/eventlog/subscriptions/SubscriptionsEndpoint.scala
event-log/src/main/scala/io/renku/eventlog/subscriptions/awaitinggeneration/AwaitingGenerationEventFinder.scala
event-log/src/main/scala/io/renku/eventlog/subscriptions/awaitinggeneration/ProjectPrioritisation.scala
event-log/src/main/scala/io/renku/eventlog/subscriptions/awaitinggeneration/SubscriptionCategory.scala
event-log/src/main/scala/io/renku/eventlog/subscriptions/awaitinggeneration/SubscriptionCategoryPayload.scala
event-log/src/main/scala/io/renku/eventlog/subscriptions/membersync/SubscriptionCategoryPayload.scala
event-log/src/main/scala/io/renku/eventlog/subscriptions/model.scala
event-log/src/main/scala/io/renku/eventlog/subscriptions/triplesgenerated/SubscriptionCategory.scala
event-log/src/main/scala/io/renku/eventlog/subscriptions/triplesgenerated/SubscriptionCategoryPayload.scala
event-log/src/test/scala/io/renku/eventlog/subscriptions/EventsDistributorSpec.scala
event-log/src/test/scala/io/renku/eventlog/subscriptions/Generators.scala
event-log/src/test/scala/io/renku/eventlog/subscriptions/SubscribersRegistrySpec.scala
event-log/src/test/scala/io/renku/eventlog/subscriptions/SubscribersSpec.scala
event-log/src/test/scala/io/renku/eventlog/subscriptions/SubscriptionCategorySpec.scala
event-log/src/test/scala/io/renku/eventlog/subscriptions/SubscriptionInfoSpec.scala
event-log/src/test/scala/io/renku/eventlog/subscriptions/SubscriptionRequestDeserializerSpec.scala
event-log/src/test/scala/io/renku/eventlog/subscriptions/SubscriptionsEndpointSpec.scala
event-log/src/test/scala/io/renku/eventlog/subscriptions/awaitinggeneration/AwaitingGenerationEventFinderSpec.scala
event-log/src/test/scala/io/renku/eventlog/subscriptions/awaitinggeneration/ProjectPrioritisationSpec.scala
triples-generator/src/main/scala/ch/datascience/triplesgenerator/events/subscriptions/SubscriptionMechanism.scala
triples-generator/src/test/scala/ch/datascience/triplesgenerator/events/subscriptions/SubscriptionMechanismSpec.scala
version.sbt

fix: events prioritisation tweaks

---

event-log/src/main/resources/application.conf
graph-commons/src/main/resources/application.conf
helm-chart/renku-graph/templates/event-log-deployment.yaml
triples-generator/src/main/resources/application.conf
version.sbt

fix: missing config entries

---

event-log/README.md
event-log/src/main/scala/io/renku/eventlog/subscriptions/EventProducersRegistry.scala
event-log/src/main/scala/io/renku/eventlog/subscriptions/commitsync/CommitSyncEvent.scala
event-log/src/main/scala/io/renku/eventlog/subscriptions/commitsync/CommitSyncEventFinder.scala
event-log/src/main/scala/io/renku/eventlog/subscriptions/commitsync/SubscriptionCategory.scala
event-log/src/main/scala/io/renku/eventlog/subscriptions/commitsync/SubscriptionCategoryPayload.scala
event-log/src/main/scala/io/renku/eventlog/subscriptions/commitsync/package.scala
event-log/src/test/scala/io/renku/eventlog/subscriptions/commitsync/CommitSyncEventEncoderSpec.scala
event-log/src/test/scala/io/renku/eventlog/subscriptions/commitsync/CommitSyncEventFinderSpec.scala
event-log/src/test/scala/io/renku/eventlog/subscriptions/commitsync/CommitSyncEventSpec.scala
event-log/src/test/scala/io/renku/eventlog/subscriptions/commitsync/Generators.scala
event-log/src/test/scala/io/renku/eventlog/subscriptions/membersync/MemberSyncEventFinderSpec.scala
graph-commons/src/test/scala/ch/datascience/generators/Generators.scala
version.sbt

feat: new COMMIT_SYNC subscription category

---

.github/workflows/test-and-deploy.yml

ci: conventional commits enforcement

---

event-log/src/main/scala/io/renku/eventlog/subscriptions/EventsDistributor.scala
event-log/src/main/scala/io/renku/eventlog/subscriptions/EventsSender.scala
event-log/src/test/scala/io/renku/eventlog/subscriptions/EventsDistributorSpec.scala
event-log/src/test/scala/io/renku/eventlog/subscriptions/EventsSenderSpec.scala

fix: BadGateway to send subscriber to the busy queue

---

helm-chart/renku-graph/templates/event-log-deployment.yaml
helm-chart/renku-graph/templates/token-repository-deployment.yaml

fix: deployment port values for postgres

---

acceptance-tests/src/test/scala/ch/datascience/graph/acceptancetests/db/EventLog.scala
acceptance-tests/src/test/scala/ch/datascience/graph/acceptancetests/db/TokenRepository.scala
event-log/src/main/scala/io/renku/eventlog/subscriptions/awaitinggeneration/AwaitingGenerationEventFinder.scala
event-log/src/main/scala/io/renku/eventlog/subscriptions/awaitinggeneration/ProjectPrioritisation.scala
event-log/src/test/scala/io/renku/eventlog/InMemoryEventLogDb.scala
event-log/src/test/scala/io/renku/eventlog/subscriptions/awaitinggeneration/AwaitingGenerationEventFinderSpec.scala
event-log/src/test/scala/io/renku/eventlog/subscriptions/awaitinggeneration/ProjectPrioritisationSpec.scala
graph-commons/src/test/scala/ch/datascience/db/DbClientSpec.scala
token-repository/src/test/scala/ch/datascience/tokenrepository/repository/InMemoryProjectsTokensDb.scala

to count all the events being currently processed.

fix: count for total occupancy is done from a query 

---

.github/workflows/test-and-deploy.yml
.github/workflows/test-and-publish.yml
.gitignore
build.sbt
graph-commons/build.sbt
graph-commons/src/main/scala/ch/datascience/http/client/RestClient.scala
graph-commons/src/test/scala/ch/datascience/http/client/RestClientSpec.scala
json-ld/build.sbt
knowledge-graph/build.sbt
project/build.properties
triples-generator/build.sbt

chore: upgrade sbt, scala, libs

---

.github/workflows/acceptance-tests.yaml
.github/workflows/test-and-deploy.yml
.github/workflows/test-and-publish.yml

chore: moving to renku-actions

---

knowledge-graph/src/main/scala/ch/datascience/knowledgegraph/datasets/rest/DatasetsFinder.scala
knowledge-graph/src/main/scala/ch/datascience/knowledgegraph/datasets/rest/ProjectDatasetsFinder.scala
knowledge-graph/src/main/scala/ch/datascience/knowledgegraph/lineage/EdgesFinder.scala
triples-generator/src/main/scala/ch/datascience/triplesgenerator/events/categories/membersync/KGProjectMembersFinder.scala
triples-generator/src/main/scala/ch/datascience/triplesgenerator/events/categories/triplesgenerated/triplescuration/persondetails/UpdatesCreator.scala

fix: 711 sparql query optimization

---

commit-event-service/src/main/scala/ch/datascience/commiteventservice/events/categories/commitsync/eventgeneration/CommitEventSynchronizer.scala
commit-event-service/src/main/scala/ch/datascience/commiteventservice/events/categories/commitsync/eventgeneration/EventDetailsFinder.scala
commit-event-service/src/test/scala/ch/datascience/commiteventservice/events/categories/commitsync/eventgeneration/CommitEventSynchronizerSpec.scala
commit-event-service/src/test/scala/ch/datascience/commiteventservice/events/categories/commitsync/eventgeneration/EventDetailsFinderSpec.scala

fix: 710 ces memory leak

---

helm-chart/renku-graph/charts/jena/templates/statefulset.yaml
triples-generator/src/main/scala/ch/datascience/triplesgenerator/events/categories/membersync/MembersSynchronizer.scala
triples-generator/src/main/scala/ch/datascience/triplesgenerator/events/categories/membersync/UpdatesCreator.scala
triples-generator/src/test/scala/ch/datascience/triplesgenerator/events/categories/membersync/MembersSynchronizerSpec.scala
triples-generator/src/test/scala/ch/datascience/triplesgenerator/events/categories/membersync/UpdatesCreatorSpec.scala

fix: 713 project member sync batch

---

knowledge-graph/src/main/scala/ch/datascience/knowledgegraph/datasets/rest/DatasetsFinder.scala

fix: free text search speed

---

knowledge-graph/src/main/scala/ch/datascience/knowledgegraph/datasets/rest/DatasetsFinder.scala

fix: dataset search query

---

event-log/src/main/scala/io/renku/eventlog/subscriptions/commitsync/CommitSyncEventFinder.scala
event-log/src/test/scala/io/renku/eventlog/subscriptions/commitsync/CommitSyncEventFinderSpec.scala

fix: event finder query not to pick up AWAITING_DELETION

---

event-log/src/main/scala/io/renku/eventlog/subscriptions/commitsync/CommitSyncEventFinder.scala
triples-generator/src/test/scala/ch/datascience/triplesgenerator/events/categories/membersync/GitLabProjectMembersFinderSpec.scala

fix: find event query speed

---

event-log/README.md
event-log/src/main/scala/io/renku/eventlog/events/categories/statuschange/AllEventsToNewUpdater.scala
event-log/src/main/scala/io/renku/eventlog/events/categories/statuschange/DBUpdater.scala
event-log/src/main/scala/io/renku/eventlog/events/categories/statuschange/EventHandler.scala
event-log/src/main/scala/io/renku/eventlog/events/categories/statuschange/ProjectEventsToNewUpdater.scala
event-log/src/main/scala/io/renku/eventlog/events/categories/statuschange/StatusChangeEvent.scala
event-log/src/main/scala/io/renku/eventlog/events/categories/statuschange/ToTriplesGeneratedUpdater.scala
event-log/src/test/scala/io/renku/eventlog/events/categories/statuschange/AllEventsToNewUpdaterSpec.scala
event-log/src/test/scala/io/renku/eventlog/events/categories/statuschange/EventHandlerSpec.scala
event-log/src/test/scala/io/renku/eventlog/events/categories/statuschange/Generators.scala
event-log/src/test/scala/io/renku/eventlog/events/categories/statuschange/ProjectEventsToNewUpdaterSpec.scala
event-log/src/test/scala/io/renku/eventlog/events/categories/statuschange/StatusChangerSpec.scala

feat: 767 el to change event status to new for a project

---

triples-generator/src/main/resources/application.conf
triples-generator/src/main/scala/io/renku/triplesgenerator/events/categories/triplesgenerated/EventProcessor.scala
triples-generator/src/main/scala/io/renku/triplesgenerator/events/categories/triplesgenerated/TransformationStep.scala
triples-generator/src/main/scala/io/renku/triplesgenerator/events/categories/triplesgenerated/triplescuration/datasets/DatasetTransformer.scala
triples-generator/src/main/scala/io/renku/triplesgenerator/events/categories/triplesgenerated/triplescuration/datasets/KGDatasetInfoFinder.scala
triples-generator/src/main/scala/io/renku/triplesgenerator/events/categories/triplesgenerated/triplescuration/datasets/UpdatesCreator.scala
triples-generator/src/main/scala/io/renku/triplesgenerator/events/categories/triplesgenerated/triplescuration/persondetails/PersonTransformer.scala
triples-generator/src/main/scala/io/renku/triplesgenerator/events/categories/triplesgenerated/triplescuration/projects/ProjectTransformer.scala
triples-generator/src/main/scala/io/renku/triplesgenerator/events/categories/triplesgenerated/triplescuration/projects/UpdatesCreator.scala
triples-generator/src/main/scala/io/renku/triplesgenerator/events/categories/triplesgenerated/triplesuploading/TransformationStepsRunnerImpl.scala
triples-generator/src/main/scala/io/renku/triplesgenerator/events/categories/triplesgenerated/triplesuploading/TriplesUploader.scala
triples-generator/src/main/scala/io/renku/triplesgenerator/events/categories/triplesgenerated/triplesuploading/UpdatesUploader.scala
triples-generator/src/test/scala/io/renku/triplesgenerator/events/categories/triplesgenerated/EventProcessorSpec.scala
triples-generator/src/test/scala/io/renku/triplesgenerator/events/categories/triplesgenerated/triplescuration/Generators.scala
triples-generator/src/test/scala/io/renku/triplesgenerator/events/categories/triplesgenerated/triplescuration/TransformationStepSpec.scala
triples-generator/src/test/scala/io/renku/triplesgenerator/events/categories/triplesgenerated/triplescuration/datasets/DatasetTransformerSpec.scala
triples-generator/src/test/scala/io/renku/triplesgenerator/events/categories/triplesgenerated/triplescuration/datasets/KGDatasetInfoFinderSpec.scala
triples-generator/src/test/scala/io/renku/triplesgenerator/events/categories/triplesgenerated/triplescuration/datasets/UpdatesCreatorSpec.scala
triples-generator/src/test/scala/io/renku/triplesgenerator/events/categories/triplesgenerated/triplescuration/persondetails/PersonTransformerSpec.scala
triples-generator/src/test/scala/io/renku/triplesgenerator/events/categories/triplesgenerated/triplescuration/projects/ProjectTransformerSpec.scala
triples-generator/src/test/scala/io/renku/triplesgenerator/events/categories/triplesgenerated/triplesuploading/TransformationStepsRunnerSpec.scala
triples-generator/src/test/scala/io/renku/triplesgenerator/events/categories/triplesgenerated/triplesuploading/TriplesUploaderSpec.scala
triples-generator/src/test/scala/io/renku/triplesgenerator/events/categories/triplesgenerated/triplesuploading/UpdatesUploaderSpec.scala

refactor: differentiating pre and post data upload queries

---

commit-event-service/src/main/scala/io/renku/commiteventservice/events/categories/globalcommitsync/eventgeneration/ELCommitFetcher.scala
knowledge-graph/src/main/scala/io/renku/knowledgegraph/lineage/NodeDetailsFinder.scala
knowledge-graph/src/test/scala/io/renku/knowledgegraph/lineage/NodeDetailsFinderSpec.scala
renku-model/src/main/scala/io/renku/graph/model/entities/Plan.scala
renku-model/src/test/scala/io/renku/graph/model/entities/PlanSpec.scala
renku-model/src/test/scala/io/renku/graph/model/testentities/LineageExemplarData.scala
renku-model/src/test/scala/io/renku/graph/model/testentities/ModelOps.scala
renku-model/src/test/scala/io/renku/graph/model/testentities/Plan.scala
renku-model/src/test/scala/io/renku/graph/model/testentities/generators/ActivityGenerators.scala

feat: allow command to be optional

---

renku-model/src/main/scala/io/renku/graph/model/associations.scala
renku-model/src/main/scala/io/renku/graph/model/entities/Association.scala
renku-model/src/main/scala/io/renku/graph/model/entities/Entity.scala
renku-model/src/main/scala/io/renku/graph/model/entities/Project.scala
renku-model/src/test/scala/io/renku/graph/model/associationsSpec.scala
renku-model/src/test/scala/io/renku/graph/model/entities/AssociationSpec.scala
renku-model/src/test/scala/io/renku/graph/model/entities/ProjectSpec.scala
renku-model/src/test/scala/io/renku/graph/model/testentities/Association.scala
renku-model/src/test/scala/io/renku/graph/model/testentities/generators/ActivityGenerators.scala
triples-generator/src/main/resources/application.conf
triples-generator/src/main/scala/io/renku/triplesgenerator/events/categories/triplesgenerated/ProjectFunctions.scala
triples-generator/src/main/scala/io/renku/triplesgenerator/events/categories/triplesgenerated/transformation/activities/ActivityTransformer.scala
triples-generator/src/main/scala/io/renku/triplesgenerator/events/categories/triplesgenerated/transformation/activities/KGInfoFinder.scala
triples-generator/src/main/scala/io/renku/triplesgenerator/events/categories/triplesgenerated/transformation/activities/UpdatesCreator.scala
triples-generator/src/main/scala/io/renku/triplesgenerator/events/categories/triplesgenerated/transformation/datasets/DatasetTransformer.scala
triples-generator/src/test/scala/io/renku/triplesgenerator/events/categories/triplesgenerated/ProjectFunctionsSpec.scala
triples-generator/src/test/scala/io/renku/triplesgenerator/events/categories/triplesgenerated/transformation/activities/ActivityTransformerSpec.scala
triples-generator/src/test/scala/io/renku/triplesgenerator/events/categories/triplesgenerated/transformation/activities/KGInfoFinderSpec.scala
triples-generator/src/test/scala/io/renku/triplesgenerator/events/categories/triplesgenerated/transformation/activities/UpdatesCreatorSpec.scala

nothing to add to the PR title

fix: transformation flow to support Association with Person agent

---

event-log/src/main/scala/io/renku/eventlog/init/DbInitializer.scala
event-log/src/test/scala/io/renku/eventlog/init/DbInitializerSpec.scala
triples-generator/src/main/resources/application.conf

feat: eventlog recovery mechanism for db migrations

---

acceptance-tests/project/build.properties
commit-event-service/Dockerfile
event-log/Dockerfile
knowledge-graph/Dockerfile
project/build.properties
token-repository/Dockerfile
triples-generator/Dockerfile
webhook-service/Dockerfile

chore: updated sbt version

---

commit-event-service/Dockerfile
event-log/Dockerfile
knowledge-graph/Dockerfile
token-repository/Dockerfile
triples-generator/Dockerfile
webhook-service/Dockerfile
webhook-service/README.md

chore: KG services not to be run by root

---

event-log/src/main/scala/io/renku/eventlog/events/categories/statuschange/EventHandler.scala
event-log/src/main/scala/io/renku/eventlog/events/categories/statuschange/StatusChangeEvent.scala
event-log/src/main/scala/io/renku/eventlog/events/categories/statuschange/ToFailureUpdater.scala
event-log/src/test/scala/io/renku/eventlog/events/categories/statuschange/EventHandlerSpec.scala
event-log/src/test/scala/io/renku/eventlog/events/categories/statuschange/Generators.scala
event-log/src/test/scala/io/renku/eventlog/events/categories/statuschange/StatusChangerSpec.scala
event-log/src/test/scala/io/renku/eventlog/events/categories/statuschange/ToFailureUpdaterSpec.scala
triples-generator/src/main/scala/io/renku/triplesgenerator/events/categories/EventStatusUpdater.scala
triples-generator/src/main/scala/io/renku/triplesgenerator/events/categories/awaitinggeneration/CommitEventProcessor.scala
triples-generator/src/main/scala/io/renku/triplesgenerator/events/categories/triplesgenerated/EventProcessor.scala
triples-generator/src/test/scala/io/renku/triplesgenerator/events/categories/awaitinggeneration/CommitEventProcessorSpec.scala
triples-generator/src/test/scala/io/renku/triplesgenerator/events/categories/cleanup/EventHandlerSpec.scala
triples-generator/src/test/scala/io/renku/triplesgenerator/events/categories/triplesgenerated/EventProcessorSpec.scala

fix: delay execution of recoverably failed events
closes #802

fix: delay execution of recoverably failed events

---

commit-event-service/Dockerfile
event-log/Dockerfile
knowledge-graph/Dockerfile
token-repository/Dockerfile
triples-generator/Dockerfile
webhook-service/Dockerfile

closes #805 
/deploy renku=1.0-next renku-ui=1.0-next renku-core=develop

chore: 805 docker init process

---

renku-model/src/main/scala/io/renku/graph/model/entities/Dataset.scala
renku-model/src/test/scala/io/renku/graph/model/entities/DatasetSpec.scala

fix: triples transformation to recover modified DS without derivedFrom

---

knowledge-graph/src/main/scala/io/renku/knowledgegraph/datasets/rest/DatasetsFinder.scala
knowledge-graph/src/test/scala/io/renku/knowledgegraph/datasets/rest/DatasetsFinderSpec.scala

This PR addresses slowness of the free-text DS search

fix: free-text DS search query perf improvements

---

webhook-service/src/main/scala/io/renku/webhookservice/hookdeletion/HookDeletionEndpoint.scala
webhook-service/src/main/scala/io/renku/webhookservice/hookfetcher/ProjectHookFetcher.scala
webhook-service/src/test/scala/io/renku/webhookservice/hookfetcher/ProjectHookFetcherSpec.scala

fix: handling of removed project on webhook fetcher service

---

event-log/src/main/scala/io/renku/eventlog/events/categories/statuschange/EventHandler.scala
event-log/src/main/scala/io/renku/eventlog/events/categories/statuschange/ProjectEventsToNewUpdater.scala
event-log/src/test/scala/io/renku/eventlog/events/categories/statuschange/ProjectEventsToNewUpdaterSpec.scala

This PR tweaks the `STATUS_CHANGE_EVENT` changing all project's events to `NEW` so it removes all `AWAITING_GENERATION` events belonging to it.

fix: event changing project events to NEW to remove AWAITING_DELETION

---

README.md

docs: added project re-provisioning explanations

docs: added project re-provisioning explanations

---

helm-chart/renku-graph/templates/commit-event-service-deployment.yaml
helm-chart/renku-graph/templates/event-log-deployment.yaml
helm-chart/renku-graph/templates/knowledge-graph-deployment.yaml
helm-chart/renku-graph/templates/token-repository-deployment.yaml
helm-chart/renku-graph/templates/triples-generator-deployment.yaml
helm-chart/renku-graph/templates/webhook-service-deployment.yaml
helm-chart/renku-graph/values.yaml

Align sentry values with the other renku repositories.
Reference: https://swiss-data-science.slack.com/archives/G67N59QL8/p1643901194490749
/deploy

build: update sentry values

---

event-log/src/main/scala/io/renku/eventlog/subscriptions/globalcommitsync/DispatchRecovery.scala
event-log/src/main/scala/io/renku/eventlog/subscriptions/globalcommitsync/GlobalCommitSyncEventFinder.scala
event-log/src/main/scala/io/renku/eventlog/subscriptions/globalcommitsync/LastSyncedDateUpdater.scala
event-log/src/test/scala/io/renku/eventlog/subscriptions/globalcommitsync/LastSyncedDateUpdaterSpec.scala

fix: global commit sync finder not to throw error when project gone

---

triples-generator/src/main/scala/io/renku/triplesgenerator/events/categories/awaitinggeneration/triplesgeneration/renkulog/Commands.scala
triples-generator/src/test/scala/io/renku/triplesgenerator/events/categories/awaitinggeneration/triplesgeneration/renkulog/GitSpec.scala

fix: auth related cloning issues to become AuthRecoverableErrors

---

event-log/src/main/scala/io/renku/eventlog/events/categories/statuschange/EventHandler.scala
event-log/src/main/scala/io/renku/eventlog/events/categories/statuschange/StatusChangeEvent.scala
event-log/src/main/scala/io/renku/eventlog/events/categories/zombieevents/EventHandler.scala
event-log/src/test/scala/io/renku/eventlog/events/categories/statuschange/EventHandlerSpec.scala
event-log/src/test/scala/io/renku/eventlog/events/categories/zombieevents/EventHandlerSpec.scala
graph-commons/src/main/scala/io/renku/events/consumers/EventHandler.scala

fix: reduce noise in EL logs

---

event-log/src/main/scala/io/renku/eventlog/events/categories/creation/EventPersister.scala
event-log/src/test/scala/io/renku/eventlog/events/categories/creation/EventPersisterSpec.scala

fix: event persistence to work in case of race condition

---

event-log/src/main/scala/io/renku/eventlog/events/categories/creation/EventPersister.scala
renku-model/src/main/scala/io/renku/graph/model/views/SparqlValueEncoder.scala
renku-model/src/test/scala/io/renku/graph/model/views/SparqlValueEncoderSpec.scala

fix: sparql encoder to escape '

---

triples-generator/src/main/scala/io/renku/triplesgenerator/events/categories/awaitinggeneration/triplesgeneration/renkulog/Commands.scala
triples-generator/src/main/scala/io/renku/triplesgenerator/events/categories/awaitinggeneration/triplesgeneration/renkulog/RenkuLogTriplesGenerator.scala
triples-generator/src/test/scala/io/renku/triplesgenerator/events/categories/awaitinggeneration/triplesgeneration/renkulog/RenkuLogTriplesGeneratorSpec.scala

fix: triples generation not to fail when repo is dirty after checkout

---

event-log/src/main/scala/io/renku/eventlog/init/DbInitializer.scala
triples-generator/src/main/scala/io/renku/triplesgenerator/events/categories/triplesgenerated/projectinfo/ProjectInfoFinder.scala
triples-generator/src/test/scala/io/renku/triplesgenerator/events/categories/triplesgenerated/projectinfo/ProjectInfoFinderSpec.scala

fix: transformation flow to deduplicate different members with the same id

---

graph-commons/src/main/scala/io/renku/graph/http/server/security/Authorizer.scala
graph-commons/src/main/scala/io/renku/graph/http/server/security/DatasetIdRecordsFinder.scala
graph-commons/src/test/scala/io/renku/graph/http/server/security/AuthorizerSpec.scala
knowledge-graph/src/main/scala/io/renku/knowledgegraph/datasets/rest/BaseDetailsFinder.scala
knowledge-graph/src/main/scala/io/renku/knowledgegraph/datasets/rest/CreatorsFinder.scala

fix: authorizer to work with security records with mixed visibility

---

event-log/src/main/scala/io/renku/eventlog/init/DbInitializer.scala
triples-generator/src/main/scala/io/renku/triplesgenerator/events/categories/awaitinggeneration/triplesgeneration/renkulog/Commands.scala
triples-generator/src/main/scala/io/renku/triplesgenerator/events/categories/awaitinggeneration/triplesgeneration/renkulog/RenkuLogTriplesGenerator.scala

fix: dirty repo cleaning problem

---

acceptance-tests/src/test/scala/io/renku/graph/acceptancetests/stubs/GitLab.scala
commit-event-service/src/main/scala/io/renku/commiteventservice/events/categories/globalcommitsync/eventgeneration/CommitsSynchronizer.scala
commit-event-service/src/main/scala/io/renku/commiteventservice/events/categories/globalcommitsync/eventgeneration/ELCommitFetcher.scala
commit-event-service/src/main/scala/io/renku/commiteventservice/events/categories/globalcommitsync/eventgeneration/gitlab/GitLabCommitFetcher.scala
commit-event-service/src/main/scala/io/renku/commiteventservice/events/categories/globalcommitsync/eventgeneration/model.scala
commit-event-service/src/test/scala/io/renku/commiteventservice/events/categories/globalcommitsync/Generators.scala
commit-event-service/src/test/scala/io/renku/commiteventservice/events/categories/globalcommitsync/eventgeneration/CommitsSynchronizerSpec.scala
commit-event-service/src/test/scala/io/renku/commiteventservice/events/categories/globalcommitsync/eventgeneration/DateConditionSpec.scala
commit-event-service/src/test/scala/io/renku/commiteventservice/events/categories/globalcommitsync/eventgeneration/ELCommitFetcherSpec.scala
commit-event-service/src/test/scala/io/renku/commiteventservice/events/categories/globalcommitsync/eventgeneration/gitlab/GitLabCommitFetcherSpec.scala
event-log/README.md
event-log/src/main/scala/io/renku/eventlog/MicroserviceRoutes.scala
event-log/src/main/scala/io/renku/eventlog/events/EventsEndpoint.scala
event-log/src/main/scala/io/renku/eventlog/events/EventsFinder.scala
event-log/src/test/scala/io/renku/eventlog/MicroserviceRoutesSpec.scala
event-log/src/test/scala/io/renku/eventlog/events/EventsEndpointSpec.scala
event-log/src/test/scala/io/renku/eventlog/events/EventsFinderSpec.scala

fix: global_commit_sync to work when events come during processing

---

event-log/src/main/scala/io/renku/eventlog/events/categories/statuschange/EventHandler.scala
event-log/src/main/scala/io/renku/eventlog/events/categories/statuschange/GaugesUpdater.scala
event-log/src/main/scala/io/renku/eventlog/events/categories/statuschange/ProjectEventsToNewUpdater.scala
event-log/src/test/scala/io/renku/eventlog/events/categories/statuschange/ProjectEventsToNewUpdaterSpec.scala
knowledge-graph/src/test/scala/io/renku/knowledgegraph/entities/finder/EntitiesFinderSpec.scala

fix: Project Events To New not to remove GENERATING_TRIPLES
