- helm-chart/renku-graph/templates/deployment.yaml
As we would like to have different datasets per developer on a shared Jena in the `dev` environment, it has to be possible for the `triples-generator`s to create datasets with certain names. As `triples-generator` was already configurable to do that, a tiny tweak to its helm chart had to be done.
> Inject JENA_DATASET_NAME to `triples-generator` during deployment

- graph-commons/src/test/scala/ch/datascience/controllers/ErrorMessageSpec.scala
- webhook-service/README.md
- webhook-service/app/ch/datascience/webhookservice/hookcreation/HookCreator.scala
- webhook-service/app/ch/datascience/webhookservice/hookcreation/ProjectHookCreator.scala
- webhook-service/app/ch/datascience/webhookservice/hookvalidation/HookValidationEndpoint.scala
- webhook-service/app/ch/datascience/webhookservice/hookvalidation/HookValidator.scala
- webhook-service/app/ch/datascience/webhookservice/hookvalidation/ProjectHookVerifier.scala
- webhook-service/app/ch/datascience/webhookservice/model.scala
- webhook-service/app/ch/datascience/webhookservice/project/ProjectHookUrlFinder.scala
- webhook-service/app/ch/datascience/webhookservice/project/ProjectHookVerifier.scala
- webhook-service/app/ch/datascience/webhookservice/project/ProjectInfoFinder.scala
- webhook-service/app/ch/datascience/webhookservice/project/SelfUrlConfig.scala
- webhook-service/app/ch/datascience/webhookservice/security/AccessTokenFinder.scala
- webhook-service/conf/routes
- webhook-service/test/ch/datascience/webhookservice/ProjectVisibilitySpec.scala
- webhook-service/test/ch/datascience/webhookservice/generators/ServiceTypesGenerators.scala
- webhook-service/test/ch/datascience/webhookservice/hookcreation/HookCreationGenerators.scala
- webhook-service/test/ch/datascience/webhookservice/hookcreation/HookCreatorSpec.scala
- webhook-service/test/ch/datascience/webhookservice/hookcreation/ProjectHookUrlSpec.scala
- webhook-service/test/ch/datascience/webhookservice/hookvalidation/HookValidationEndpointSpec.scala
- webhook-service/test/ch/datascience/webhookservice/hookvalidation/HookValidatorSpec.scala
- webhook-service/test/ch/datascience/webhookservice/hookvalidation/IOProjectHookVerifierSpec.scala
- webhook-service/test/ch/datascience/webhookservice/project/IOProjectHookVerifierSpec.scala
- webhook-service/test/ch/datascience/webhookservice/project/IOProjectInfoFinderSpec.scala
- webhook-service/test/ch/datascience/webhookservice/project/ProjectHookUrlFinderSpec.scala
- webhook-service/test/ch/datascience/webhookservice/project/SelfUrlConfigProviderSpec.scala
- webhook-service/test/ch/datascience/webhookservice/security/AccessTokenFinderSpec.scala
As a `webhook-service` user I need a POST /projects/:id/webhooks/validation which checks if there's a webhook created for a project with the given id.
Testing
The endpoint should respond with:
200 - if project has the webhook
404 - if there's no webhook
401 - if the given access tokens are missing or invalid
500 - for non-public projects or if there's an error during the check
> POST /projects/:id/webhooks/validation to work for public projects

- helm-chart/minikube-values.yaml
- helm-chart/renku-graph/templates/deployment.yaml
- helm-chart/renku-graph/templates/secret.yaml
- helm-chart/renku-graph/values.yaml
- webhook-service/conf/application.conf
This secret I forgot the other day and effectively all the environments would be using the same secret for encrypting the hook tokens send from Gitlab
> Made HOOK_TOKEN_SECRET be injected to the `webhook-service` on deploy

- helm-chart/renku-graph/templates/deployment.yaml
This is a tiny change for `global.graph.jena.dataset` default value. Instead of `renku` it defaults now to `{{ .Release.Namespace }}`.
Tested on my local `renku-kuba`.
> Defaulted jena.dataset to {{ .Release.Namespace }}

- triples-generator/src/main/resources/application.conf
This is a one-liner changing default dataset type of our Renku triples store from `mem` to `tdb` so the store gets persisted to disk instead of being just in-memory.
> Changing default dataset type from `mem` to `tdb`

- graph-commons/src/main/scala/ch/datascience/http/client/RestClientError.scala
- webhook-service/README.md
- webhook-service/src/main/scala/ch/datascience/webhookservice/security/AccessTokenExtractor.scala
- webhook-service/src/test/scala/ch/datascience/webhookservice/security/AccessTokenExtractorSpec.scala
Closes #46 and is explained there in details.
For the time being, I left the support for the `OAUTH-TOKEN` for backwards compatibility.
> OAuth access token to be passed in the Bearer

- helm-chart/renku-graph/templates/deployment.yaml
There was a problem with deploying Graph Services on UI-team environment. I found there was a wrong template linked in the `deployment.yaml` of the Graph Services so instead of `graph`, `renku` template was used.
> fix: Wrong secretKeyRef for token-repository

- db-event-log/src/test/scala/ch/datascience/dbeventlog/commands/EventLogFetchSpec.scala
- graph-commons/src/main/scala/ch/datascience/control/Throttler.scala
- graph-commons/src/test/scala/ch/datascience/control/ThrottlerSpec.scala
- triples-generator/build.sbt
There was a bug in the throttling mechanism which was suspending the rate limit when a single task was executing longer than the rate limit was set. For instance, if a rate was 2/sec and there a first scheduled task was executing for 2s and in the meantime, two other tasks arrived, the Throttler would allow them to be executed immediately after their arrival. This fix would prevent such behaviour and would allow only one of the two later tasks to be executed immediately while the other would have to wait another 500ms.
> Throttler not to pass items scheduled after a long running one

- webhook-service/README.md
- webhook-service/src/main/scala/ch/datascience/webhookservice/security/AccessTokenExtractor.scala
- webhook-service/src/test/scala/ch/datascience/webhookservice/security/AccessTokenExtractorSpec.scala
There was a PR #56 which allowed passing oauth access tokens in the Authorization: Bearer headers. This PR removes support for passing the tokens in the OAUTH-TOKEN headers.
> OAUTH-TOKEN header support removal

- db-event-log/src/main/scala/ch/datascience/dbeventlog/commands/EventLogProcessingStatus.scala
- db-event-log/src/main/scala/ch/datascience/dbeventlog/init/EventLogDbInitializer.scala
- db-event-log/src/test/scala/ch/datascience/dbeventlog/DbEventLogGenerators.scala
- db-event-log/src/test/scala/ch/datascience/dbeventlog/commands/EventLogProcessingStatusSpec.scala
- db-event-log/src/test/scala/ch/datascience/dbeventlog/commands/ProcessingStatusSpec.scala
- db-event-log/src/test/scala/ch/datascience/dbeventlog/init/EventLogDbInitializerSpec.scala
- graph-commons/src/main/scala/ch/datascience/controllers/ClientMessages.scala
- graph-commons/src/test/scala/ch/datascience/generators/Generators.scala
- webhook-service/README.md
- webhook-service/src/main/scala/ch/datascience/webhookservice/Microservice.scala
- webhook-service/src/main/scala/ch/datascience/webhookservice/MicroserviceRoutes.scala
- webhook-service/src/main/scala/ch/datascience/webhookservice/eventprocessing/ProcessingStatusEndpoint.scala
- webhook-service/src/main/scala/ch/datascience/webhookservice/hookcreation/HookCreator.scala
- webhook-service/src/main/scala/ch/datascience/webhookservice/hookvalidation/HookValidationEndpoint.scala
- webhook-service/src/main/scala/ch/datascience/webhookservice/hookvalidation/HookValidator.scala
- webhook-service/src/test/scala/ch/datascience/webhookservice/eventprocessing/HookEventEndpointSpec.scala
- webhook-service/src/test/scala/ch/datascience/webhookservice/eventprocessing/ProcessingStatusEndpointSpec.scala
- webhook-service/src/test/scala/ch/datascience/webhookservice/hookcreation/HookCreatorSpec.scala
- webhook-service/src/test/scala/ch/datascience/webhookservice/hookvalidation/HookValidationEndpointSpec.scala
- webhook-service/src/test/scala/ch/datascience/webhookservice/hookvalidation/HookValidatorSpec.scala
- webhook-service/src/test/scala/ch/datascience/webhookservice/missedevents/IOMissedEventsLoaderSpec.scala
This PR introduces a new endpoint which fetches info about events processing progress of a project with the given id.
The endpoint is accessible on the webhook-service at:
`GET <webhook-service>/projects/:id/events/status`
Valid 200 response looks like:
`{ "done": 10, "total": 20, "progress": 50.00 }`
> Events processing progress fetching endpoint

- build.sbt
- triples-generator/src/test/scala/ch/datascience/triplesgenerator/eventprocessing/triplesgeneration/renkulog/RenkuSpec.scala
It seems Travis is generating some files when running the build. This change skips them during the release process.
> fix: skipping untracked files on travis box

- graph-commons/src/test/scala/ch/datascience/rdfstore/RdfStoreData.scala
- helm-chart/renku-graph/values.yaml
- triples-generator/src/main/scala/ch/datascience/triplesgenerator/reprovisioning/OutdatedTriplesRemover.scala
- triples-generator/src/test/scala/ch/datascience/triplesgenerator/reprovisioning/IOOutdatedTriplesRemoverSpec.scala
While working on https://app.zenhub.com/workspaces/renku-platform-5d259f8758ce4031eea0908c/issues/swissdatasciencecenter/renku-graph/97 I noticed that after some changes around the dataset triples generation on `renku-python`, Triples Generator does not perform proper clean-up and some of the triples are left untouched. This PR fixes the delete query for address the issue.
This PR also enables auto re-provisioning by changing the `reProvisioningInitialDelay` from 1 year to 2 minutes.
closes #113
> fix: removing outdated dataset triples generated by renku 0.5.2

- graph-commons/src/main/scala/ch/datascience/controllers/ClientMessages.scala
- graph-commons/src/test/scala/ch/datascience/controllers/ErrorMessageSpec.scala
- graph-commons/src/test/scala/ch/datascience/http/server/EndpointTester.scala
- knowledge-graph/src/main/scala/ch/datascience/knowledgegraph/graphql/QueryEndpoint.scala
- knowledge-graph/src/test/scala/ch/datascience/knowledgegraph/graphql/QueryEndpointSpec.scala
- token-repository/src/main/scala/ch/datascience/tokenrepository/repository/association/AssociateTokenEndpoint.scala
- webhook-service/src/main/scala/ch/datascience/webhookservice/eventprocessing/HookEventEndpoint.scala
- webhook-service/src/main/scala/ch/datascience/webhookservice/eventprocessing/ProcessingStatusEndpoint.scala
- webhook-service/src/main/scala/ch/datascience/webhookservice/hookcreation/HookCreationEndpoint.scala
- webhook-service/src/main/scala/ch/datascience/webhookservice/hookvalidation/HookValidationEndpoint.scala
- webhook-service/src/test/scala/ch/datascience/webhookservice/eventprocessing/HookEventEndpointSpec.scala
- webhook-service/src/test/scala/ch/datascience/webhookservice/eventprocessing/ProcessingStatusEndpointSpec.scala
- webhook-service/src/test/scala/ch/datascience/webhookservice/hookcreation/HookCreationEndpointSpec.scala
- webhook-service/src/test/scala/ch/datascience/webhookservice/hookvalidation/HookValidationEndpointSpec.scala
It was observed that when an exception has a null message, graph-services logs a NullPointerException raised from the internals of the ErrorMessage class hiding the real exception. This PR fixes that bug and logs Exception class name instead.
> ErrorMessage hiding the real error for Exception with null message

- acceptance-tests/src/test/scala/ch/datascience/graph/acceptancetests/flows/RdfStoreProvisioning.scala
- acceptance-tests/src/test/scala/ch/datascience/graph/acceptancetests/stubs/RemoteTriplesGenerator.scala
- build.sbt
- db-event-log/src/main/scala/ch/datascience/dbeventlog/commands/EventLogMarkDone.scala
- db-event-log/src/test/scala/ch/datascience/dbeventlog/commands/EventLogMarkDoneSpec.scala
- graph-commons/src/test/scala/ch/datascience/rdfstore/triples/entities/Agent.scala
- graph-commons/src/test/scala/ch/datascience/rdfstore/triples/entities/CommitActivity.scala
- graph-commons/src/test/scala/ch/datascience/rdfstore/triples/entities/Person.scala
- graph-commons/src/test/scala/ch/datascience/rdfstore/triples/multiFileAndCommit.scala
- graph-commons/src/test/scala/ch/datascience/rdfstore/triples/package.scala
- graph-commons/src/test/scala/ch/datascience/rdfstore/triples/singleFileAndCommit.scala
- graph-commons/src/test/scala/ch/datascience/rdfstore/triples/singleFileAndCommitWithDataset.scala
- triples-generator/src/main/scala/ch/datascience/triplesgenerator/reprovisioning/OutdatedTriplesFinder.scala
- triples-generator/src/test/scala/ch/datascience/triplesgenerator/reprovisioning/IOOutdatedTriplesFinderSpec.scala
- triples-generator/src/test/scala/ch/datascience/triplesgenerator/reprovisioning/IOOutdatedTriplesRemoverSpec.scala
There was a regression bug introduced when an `rdfs:label` was introduced to the `person` entity in the KG. That broke the re-provisioning process which was looking for agent's `rdfs:label` not matching certain version of Renku CLI. That condition was simply always true as there are at least two agent triples on the commit entity one pointing to the version of Renku CLI, other pointing to people who did the commits.
closes #145
> Re-provisioning in loop

- helm-chart/renku-graph/charts/jena/templates/deployment.yaml
An unauthenticated request to `/` on jena returns a `401` which for example on minikube (but strangely enough not on our dev cluster, maybe a k8s version question) interpreted as a failed liveness- or readiness probe. This PR fixes this by using an authentication-free endpoint.
> charts: Fix liveness probe for jena

- .travis.yml
pin chartpress version to avoid using the new charts naming convention
> ci: pin chartpress version

- .travis.yml
- .travis/travis-hotfix.sh
- .travis/travis-publish.sh
- README.md
- helm-chart/renku-graph/Chart.yaml
- triples-generator/src/main/scala/ch/datascience/triplesgenerator/reprovisioning/OutdatedTriplesFinder.scala
- version.sbt
This PR is a merge with changes done for 0.10.1 hotfix described here #160.
closes #160 
closes #159
> Merge with hotfix 0.10.1

- helm-chart/renku-graph/Chart.yaml
- helm-chart/renku-graph/charts/jena/templates/fuseki-server.yaml
- version.sbt
It looks that Jena on environments having DB on persistent volumes cannot start the Lucene indexing as there's some lingering PID in the `tdb.lock` file. This PR removes the file before starting the indexing.
> Jena startup error

- helm-chart/renku-graph/Chart.yaml
- helm-chart/renku-graph/charts/jena/templates/fuseki-server.yaml
- version.sbt
It looks there is a general problem with removing the `tdb.lock` file on the DEV environment. This change removes the lock file after Lucene indexing is done.
> Jena startup problem

- acceptance-tests/src/test/scala/ch/datascience/graph/acceptancetests/knowledgegraph/DatasetsResourcesSpec.scala
- graph-commons/src/main/scala/ch/datascience/graph/model/datasets.scala
- graph-commons/src/test/scala/ch/datascience/graph/model/GraphModelGenerators.scala
- graph-commons/src/test/scala/ch/datascience/rdfstore/triples/entities/Dataset.scala
- graph-commons/src/test/scala/ch/datascience/rdfstore/triples/singleFileAndCommitWithDataset.scala
- knowledge-graph/README.md
- knowledge-graph/src/main/scala/ch/datascience/knowledgegraph/datasets/CreatorsFinder.scala
- knowledge-graph/src/main/scala/ch/datascience/knowledgegraph/datasets/graphql/BaseDetailsFinder.scala
- knowledge-graph/src/main/scala/ch/datascience/knowledgegraph/datasets/model.scala
- knowledge-graph/src/main/scala/ch/datascience/knowledgegraph/datasets/rest/BaseDetailsFinder.scala
- knowledge-graph/src/main/scala/ch/datascience/knowledgegraph/datasets/rest/DatasetEndpoint.scala
- knowledge-graph/src/main/scala/ch/datascience/knowledgegraph/datasets/rest/DatasetsSearchEndpoint.scala
- knowledge-graph/src/test/scala/ch/datascience/knowledgegraph/datasets/DatasetsGenerators.scala
- knowledge-graph/src/test/scala/ch/datascience/knowledgegraph/datasets/graphql/IOProjectDatasetsFinderSpec.scala
- knowledge-graph/src/test/scala/ch/datascience/knowledgegraph/datasets/rest/BaseDetailsFinderSpec.scala
- knowledge-graph/src/test/scala/ch/datascience/knowledgegraph/datasets/rest/DatasetEndpointSpec.scala
- knowledge-graph/src/test/scala/ch/datascience/knowledgegraph/datasets/rest/DatasetsSearchEndpointSpec.scala
- knowledge-graph/src/test/scala/ch/datascience/knowledgegraph/datasets/rest/IODatasetFinderSpec.scala
- knowledge-graph/src/test/scala/ch/datascience/knowledgegraph/datasets/rest/IODatasetsFinderSpec.scala
This PR introduces changes described in #130 
Images for testing:
```
'repository': 'jachro/token-repository', 'tag': '65a2e42'
'repository': 'jachro/webhook-service', 'tag': '65a2e42'
'repository': 'jachro/triples-generator', 'tag': '65a2e42'
'repository': 'jachro/knowledge-graph', 'tag': '65a2e42'
```
closes #130
> Add fields to dataset metadata

- helm-chart/renku-graph/Chart.yaml
- triples-generator/Dockerfile
- version.sbt
We found some tiny bug in renku-python `0.8.0` which was fixed in `0.8.1`. This PR bumps renku-python version in triples-generator's Dockerfile.
> renku-python version bumb to 0.8.1

- helm-chart/renku-graph/Chart.yaml
- triples-generator/Dockerfile
- version.sbt
This PR raises the version of renku-python used in triples-generator due to the timezone bug.
> renku-python upgrade to 0.8.2

- .travis/travis-functions.sh
This PR addresses a bug in the release process which was about CI not calling `helm dep update renku` after updating the version of renku-graph in the `requirements.yaml`.
> fix: release process to run helm dep update

- helm-chart/renku-graph/Chart.yaml
- triples-generator/src/main/scala/ch/datascience/triplesgenerator/eventprocessing/triplesgeneration/renkulog/Commands.scala
- triples-generator/src/main/scala/ch/datascience/triplesgenerator/eventprocessing/triplesgeneration/renkulog/RenkuLogTriplesGenerator.scala
- triples-generator/src/test/scala/ch/datascience/triplesgenerator/eventprocessing/triplesgeneration/renkulog/RenkuLogTriplesGeneratorSpec.scala
- triples-generator/src/test/scala/ch/datascience/triplesgenerator/eventprocessing/triplesgeneration/renkulog/RenkuSpec.scala
- triples-generator/src/test/scala/ch/datascience/triplesgenerator/eventprocessing/triplesgeneration/renkulog/package.scala
- version.sbt
It was found out that for failures in `git clone` command, triples-generator logs users' access tokens. This PR fixes that.
> Tokens in logs

- helm-chart/renku-graph/Chart.yaml
- version.sbt
- webhook-service/src/main/scala/ch/datascience/webhookservice/eventprocessing/startcommit/CommitToEventLog.scala
- webhook-service/src/test/scala/ch/datascience/webhookservice/eventprocessing/startcommit/CommitToEventLogSpec.scala
It looks webhook-service generate info log statements for cases when no Commit Events were generated. That causes some noise in the logs. This PR fixes that behaviour.
> Mute gitlab synchro logs

- helm-chart/renku-graph/Chart.yaml
- triples-generator/src/main/scala/ch/datascience/triplesgenerator/eventprocessing/triplesuploading/TriplesUploader.scala
- triples-generator/src/test/scala/ch/datascience/triplesgenerator/eventprocessing/triplesuploading/TriplesUploaderSpec.scala
- version.sbt
It looks that for some malformed json-ld payloads Jena responds with 500 instead of 400. This PR fixes the way triples-generator deals with that so events for which `renku log` produces such payloads won't get re-processed.
closes #202
> Triples error wrongly classified

- .travis/travis-publish.sh
- .travis/travis-release.sh
- acceptance-tests/src/test/resources/application.conf
- helm-chart/renku-graph/templates/triples-generator-deployment.yaml
- helm-chart/renku-graph/values.yaml
- knowledge-graph/src/main/scala/ch/datascience/knowledgegraph/datasets/rest/BaseDetailsFinder.scala
- knowledge-graph/src/main/scala/ch/datascience/knowledgegraph/datasets/rest/CreatorsFinder.scala
- knowledge-graph/src/main/scala/ch/datascience/knowledgegraph/datasets/rest/DatasetsFinder.scala
- knowledge-graph/src/main/scala/ch/datascience/knowledgegraph/datasets/rest/PartsFinder.scala
- knowledge-graph/src/main/scala/ch/datascience/knowledgegraph/datasets/rest/ProjectDatasetsFinder.scala
- knowledge-graph/src/main/scala/ch/datascience/knowledgegraph/datasets/rest/ProjectsFinder.scala
- knowledge-graph/src/main/scala/ch/datascience/knowledgegraph/lineage/LineageFinder.scala
- knowledge-graph/src/main/scala/ch/datascience/knowledgegraph/projects/rest/KGProjectFinder.scala
- knowledge-graph/src/test/scala/ch/datascience/knowledgegraph/lineage/IOLineageFinderSpec.scala
- triples-generator/src/main/resources/application.conf
- triples-generator/src/main/scala/ch/datascience/triplesgenerator/eventprocessing/DbEventProcessorRunner.scala
- triples-generator/src/main/scala/ch/datascience/triplesgenerator/eventprocessing/triplescuration/PersonDetailsUpdater.scala
- triples-generator/src/main/scala/ch/datascience/triplesgenerator/reprovisioning/OutdatedTriplesRemover.scala
- triples-generator/src/main/scala/ch/datascience/triplesgenerator/reprovisioning/TriplesVersionFinder.scala
- triples-generator/src/test/scala/ch/datascience/triplesgenerator/eventprocessing/DbEventProcessorRunnerSpec.scala
- triples-generator/src/test/scala/ch/datascience/triplesgenerator/reprovisioning/IOTriplesVersionFinderSpec.scala
This PR:
* optimizes dataset's projects finding query
* improves `query_id` naming to make queries groups more visible
* prevents travis from building a chart on non-tag events
* explains free-text dataset search queries
> find dataset's projects query improvements

- acceptance-tests/src/test/scala/ch/datascience/graph/acceptancetests/knowledgegraph/LineageQuerySpec.scala
- helm-chart/renku-graph/Chart.yaml
- knowledge-graph/src/main/scala/ch/datascience/knowledgegraph/lineage/LineageFinder.scala
- knowledge-graph/src/main/scala/ch/datascience/knowledgegraph/lineage/graphql/modelSchema.scala
- knowledge-graph/src/main/scala/ch/datascience/knowledgegraph/lineage/model.scala
- knowledge-graph/src/test/scala/ch/datascience/knowledgegraph/graphql/QuerySchemaSpec.scala
- knowledge-graph/src/test/scala/ch/datascience/knowledgegraph/lineage/IOLineageFinderSpec.scala
- knowledge-graph/src/test/scala/ch/datascience/knowledgegraph/lineage/LineageGenerators.scala
- knowledge-graph/src/test/scala/ch/datascience/knowledgegraph/lineage/LineageSpec.scala
- triples-generator/Dockerfile
- version.sbt
This PR:
* changes the lineage resource so it doesn't show the `renku update` nodes;
* bumps the version of `renku-python` in `triples-generator` to `0.9.1`;
Closes #169
> lineage not to show renku updates

- graph-commons/src/main/scala/ch/datascience/graph/model/events.scala
- graph-commons/src/main/scala/ch/datascience/graph/model/users.scala
- graph-commons/src/test/scala/ch/datascience/graph/model/EventsGenerators.scala
- graph-commons/src/test/scala/ch/datascience/graph/model/eventsSpec.scala
- graph-commons/src/test/scala/ch/datascience/graph/model/usersSpec.scala
- webhook-service/src/main/scala/ch/datascience/webhookservice/commits/CommitInfo.scala
- webhook-service/src/main/scala/ch/datascience/webhookservice/eventprocessing/commitevent/CommitEventSerializer.scala
- webhook-service/src/test/scala/ch/datascience/webhookservice/commits/CommitInfoSpec.scala
- webhook-service/src/test/scala/ch/datascience/webhookservice/commits/IOCommitInfoFinderSpec.scala
- webhook-service/src/test/scala/ch/datascience/webhookservice/commits/IOLatestCommitFinderSpec.scala
- webhook-service/src/test/scala/ch/datascience/webhookservice/commits/package.scala
- webhook-service/src/test/scala/ch/datascience/webhookservice/eventprocessing/commitevent/CommitEventSerializerSpec.scala
- webhook-service/src/test/scala/ch/datascience/webhookservice/eventprocessing/startcommit/CommitToEventLogSpec.scala
- webhook-service/src/test/scala/ch/datascience/webhookservice/generators/WebhookServiceGenerators.scala
closes #244 
Images to test with:
```
'repository': 'jachro/token-repository', 'tag': '557df698'
'repository': 'jachro/webhook-service', 'tag': '653d787c'
'repository': 'jachro/triples-generator', 'tag': '557df698'
'repository': 'jachro/knowledge-graph', 'tag': '557df698'
```
> fix: allow blanks in Commit's author and committer email and username

- acceptance-tests/src/test/scala/ch/datascience/graph/acceptancetests/knowledgegraph/DatasetsResourcesSpec.scala
- acceptance-tests/src/test/scala/ch/datascience/graph/acceptancetests/knowledgegraph/ProjectsResourcesSpec.scala
- acceptance-tests/src/test/scala/ch/datascience/graph/acceptancetests/stubs/GitLab.scala
- acceptance-tests/src/test/scala/ch/datascience/graph/acceptancetests/stubs/RemoteTriplesGenerator.scala
- graph-commons/src/test/scala/ch/datascience/rdfstore/entities/Project.scala
- graph-commons/src/test/scala/ch/datascience/rdfstore/entities/bundles.scala
- helm-chart/renku-graph/Chart.yaml
- knowledge-graph/README.md
- knowledge-graph/src/main/scala/ch/datascience/knowledgegraph/projects/model.scala
- knowledge-graph/src/main/scala/ch/datascience/knowledgegraph/projects/rest/KGProjectFinder.scala
- knowledge-graph/src/main/scala/ch/datascience/knowledgegraph/projects/rest/ProjectEndpoint.scala
- knowledge-graph/src/main/scala/ch/datascience/knowledgegraph/projects/rest/ProjectFinder.scala
- knowledge-graph/src/test/scala/ch/datascience/knowledgegraph/projects/ProjectsGenerators.scala
- knowledge-graph/src/test/scala/ch/datascience/knowledgegraph/projects/rest/IOKGProjectFinderSpec.scala
- knowledge-graph/src/test/scala/ch/datascience/knowledgegraph/projects/rest/ProjectEndpointSpec.scala
- knowledge-graph/src/test/scala/ch/datascience/knowledgegraph/projects/rest/ProjectFinderSpec.scala
- triples-generator/src/main/scala/ch/datascience/triplesgenerator/eventprocessing/triplescuration/forks/ForkInfoUpdater.scala
- triples-generator/src/main/scala/ch/datascience/triplesgenerator/eventprocessing/triplescuration/forks/GitLabInfoFinder.scala
- triples-generator/src/main/scala/ch/datascience/triplesgenerator/eventprocessing/triplescuration/forks/KGInfoFinder.scala
- triples-generator/src/main/scala/ch/datascience/triplesgenerator/eventprocessing/triplescuration/forks/model.scala
- triples-generator/src/test/scala/ch/datascience/triplesgenerator/eventprocessing/triplescuration/forks/ForkInfoUpdaterSpec.scala
- triples-generator/src/test/scala/ch/datascience/triplesgenerator/eventprocessing/triplescuration/forks/GitLabInfoFinderSpec.scala
- triples-generator/src/test/scala/ch/datascience/triplesgenerator/eventprocessing/triplescuration/forks/KGInfoFinderSpec.scala
- triples-generator/src/test/scala/ch/datascience/triplesgenerator/eventprocessing/triplescuration/forks/ProjectPropertiesRemoverSpec.scala
- triples-generator/src/test/scala/ch/datascience/triplesgenerator/eventprocessing/triplescuration/forks/UpdatesCreatorSpec.scala
- triples-generator/src/test/scala/ch/datascience/triplesgenerator/eventprocessing/triplescuration/forks/package.scala
- triples-generator/src/test/scala/ch/datascience/triplesgenerator/eventprocessing/triplescuration/persondetails/PersonDetailsUpdaterSpec.scala
- triples-generator/src/test/scala/ch/datascience/triplesgenerator/reprovisioning/IOTriplesVersionFinderSpec.scala
- version.sbt
There are cases when GitLab does not return `creator_id` when calling the projects API. This PR makes the project creator info optional in KG.
**Testing scenario:**
* The easiest way to verify the fix works is to look at the outcome of the re-provisioning process on the DEV. Effectively, before the fix, 10.5K of 16K events failed during the process.
> fix: triples generation process does not work when no creator in gitlab

- db-event-log/src/main/scala/ch/datascience/dbeventlog/commands/EventLogFetch.scala
- db-event-log/src/test/scala/ch/datascience/dbeventlog/commands/EventLogFetchSpec.scala
- graph-commons/src/test/scala/ch/datascience/graph/model/EventsGenerators.scala
- helm-chart/renku-graph/Chart.yaml
- helm-chart/renku-graph/values.yaml
- knowledge-graph/src/main/scala/ch/datascience/knowledgegraph/projects/rest/ProjectEndpoint.scala
- triples-generator/src/main/scala/ch/datascience/triplesgenerator/reprovisioning/ReProvisioning.scala
- triples-generator/src/test/scala/ch/datascience/triplesgenerator/reprovisioning/ReProvisioningSpec.scala
- triples-generator/src/test/scala/ch/datascience/triplesgenerator/reprovisioning/interpreters.scala
- version.sbt
**Testing scenario:**
Simply watch the outcome of the re-provisioning on the DEV.
**Image for testing:**
```{'repository': 'jachro/triples-generator', 'tag': 'f160523a'}```
closes #290
> triples-generator hangs on events with PROCESSING status

- helm-chart/renku-graph/Chart.yaml
- helm-chart/renku-graph/charts/jena/values.yaml
- version.sbt
It looks like the defaults for `jvmXmx` as well as `users` are wrongly nested under `jena` in the Jena chart `values.yaml`. This PR fixes that.
> Jena jvmXmx and users in the chart values.yaml

- helm-chart/renku-graph/Chart.yaml
- helm-chart/renku-graph/charts/jena/values.yaml
- triples-generator/src/main/scala/ch/datascience/triplesgenerator/reprovisioning/OutdatedTriplesRemover.scala
- triples-generator/src/main/scala/ch/datascience/triplesgenerator/reprovisioning/TriplesRemover.scala
- version.sbt
As described in #302 the `CLEAR DEFAULT` operation does not seem to work in all Jena instances. This PR fixes that with a simple `DELETE` query removing batches of triples until the dataset is empty. The batching approach is needed from Jena's health point of view as it can simply blow up when trying to remove all the triples in one go.
**Testing image:**
`'repository': 'jachro/triples-generator', 'tag': 'f2a52b79'`
This image was already successfully tested on `renku-kuba`.
**Testing scenarios:**
* simply drop mentioned image to an environment of your choice and observe the [Grafana Event Log metrics](https://grafana.dev.renku.ch/d/cb9J1WBZz/event-log?orgId=1&from=now-1h&to=now&refresh=30s&var-kube_env_name=renku-kuba-renku) to see if all the events get re-scheduled for re-processing. …
> All triples removal bug

- helm-chart/renku-graph/Chart.yaml
- triples-generator/Dockerfile
- triples-generator/src/main/scala/ch/datascience/triplesgenerator/eventprocessing/triplescuration/persondetails/PersonDetailsUpdater.scala
- version.sbt
This hotfix on renku-python fixes missing properties on the SoftwareAgent Person entity.
For more details see [this](https://github.com/SwissDataScienceCenter/renku-python/pull/1323).
> renku-python upgrade to a hotfix of 0.10.4

- helm-chart/renku-graph/Chart.yaml
- helm-chart/renku-graph/charts/jena/values.yaml
- version.sbt
**Motivation**
A Jena pod has been recently evicted because there was not enough memory in the node, but the requests were 0. This should never be the case since we are requesting 2GB for the JVM by default.
**Proposal**
The CPU proposed time is more than what has been observed in production (near 0.08).
The memory proposed request is 1GB more than what JVM uses and ~0.5GB more than observed in production.
> charts: add requests for jena

- helm-chart/renku-graph/Chart.yaml
- triples-generator/Dockerfile
- version.sbt
This PR bumps the version of renku-python to v0.10.5
> chore: renku-python pinned to v0.10.5

- .dockerignore
- helm-chart/chartpress.yaml
- helm-chart/renku-graph/Chart.yaml
- helm-chart/renku-graph/templates/triples-generator-deployment.yaml
- helm-chart/renku-graph/values.yaml
- triples-generator/Dockerfile
- triples-generator/entrypoint.sh
- version.sbt
closes #161 
The intended use here is that it shouldn't be necessary to rebuild the triples generator image to test compatibility with a development version of renku-python. Note that the "version" should be  a fully-qualified pip-installable target, e.g.
```
renku==0.10.5
git+https://github.com/swissdatasciencecenter/renku-pyhon@<branch>#egg=renku
```
This image is currently deployed as the TG of rok.dev.renku.ch.
> build: allow renku-python version override

- .travis.yml
- helm-chart/renku-graph/Chart.yaml
- triples-generator/Dockerfile
- version.sbt
It looks the docker version on `chartpress` is not pinned so the CI builds stopped to work when a new python docker lib got released.
> Fix for a CI and docker issues

- .travis.yml
- .travis/travis-functions.sh
- acceptance-tests/src/test/scala/ch/datascience/graph/acceptancetests/tooling/RDFStore.scala
- graph-commons/src/test/scala/ch/datascience/rdfstore/RdfStoreServer.scala
- graph-commons/src/test/scala/ch/datascience/rdfstore/entities/bundles.scala
- helm-chart/renku-graph/Chart.yaml
- helm-chart/renku-graph/charts/jena/templates/lucene-config.yaml
- knowledge-graph/README.md
- knowledge-graph/src/main/scala/ch/datascience/knowledgegraph/datasets/model.scala
- knowledge-graph/src/main/scala/ch/datascience/knowledgegraph/datasets/rest/BaseDetailsFinder.scala
- knowledge-graph/src/main/scala/ch/datascience/knowledgegraph/datasets/rest/DatasetEndpoint.scala
- knowledge-graph/src/main/scala/ch/datascience/knowledgegraph/datasets/rest/DatasetFinder.scala
- knowledge-graph/src/test/scala/ch/datascience/knowledgegraph/datasets/DatasetsGenerators.scala
- knowledge-graph/src/test/scala/ch/datascience/knowledgegraph/datasets/rest/BaseDetailsFinderSpec.scala
- knowledge-graph/src/test/scala/ch/datascience/knowledgegraph/datasets/rest/DatasetEndpointSpec.scala
- knowledge-graph/src/test/scala/ch/datascience/knowledgegraph/datasets/rest/IODatasetFinderSpec.scala
- version.sbt
Added proper index in Jena for schema:alternateName. Returning schema:keywords when querying dataset details
> Fix 339 dataset keywords

- helm-chart/renku-graph/Chart.yaml
- triples-generator/Dockerfile
- version.sbt
There's a problem with sentry-sdk 0.19.0 and renku 0.11.4 so this PR pins version of the sdk to one that works.
> chore: sentry-sdk pinned to 0.18.0

- helm-chart/renku-graph/Chart.yaml
- triples-generator/src/main/scala/ch/datascience/triplesgenerator/eventprocessing/triplesgeneration/renkulog/Commands.scala
- triples-generator/src/test/scala/ch/datascience/triplesgenerator/eventprocessing/triplesgeneration/renkulog/GitSpec.scala
- version.sbt
It looks like errors like this:
```
Failed to connect to renkulab.io port 443: Host is unreachable
```
happening during `git clone` operation on the triples-generator are classified as non-recoverable while they should be recoverable.
> fix: cloning to classify connectivity issues as Recoverable

- event-log/src/main/scala/io/renku/eventlog/subscriptions/SubscribersRegistry.scala
- helm-chart/renku-graph/Chart.yaml
- version.sbt
There's a tiny problem which causes huge memory leak on event-log. The SubscribersRegistry creates a new thread each time it checks if there are subscribers in the busy pool.
> Memory leak on event-log

- event-log/src/main/scala/io/renku/eventlog/subscriptions/EventFetcher.scala
- helm-chart/renku-graph/Chart.yaml
- version.sbt
It looks like the new improved query for selecting the oldest non-processed event did not work with events having the same date created.
> Event fetcher bug

- event-log/src/main/scala/io/renku/eventlog/subscriptions/EventFetcher.scala
- helm-chart/renku-graph/Chart.yaml
- version.sbt
It looks the sorting done in the view does not guarantee the projects waiting in the queue are fetched in the right order.
> fix: event fetcher to sort the projests int the queue

- event-log/src/main/scala/io/renku/eventlog/subscriptions/EventFetcher.scala
- helm-chart/renku-graph/Chart.yaml
- helm-chart/renku-graph/values.yaml
- triples-generator/src/main/resources/application.conf
- version.sbt
It looks two timeouts are currently too short:
* `renku-log-timeout` set to one hour causes events to fail when they could succeed if allowed to run longer;
* `maxProcessingTime` causes same events to be processed several times in different TGs.
Both the values get extended as part of the PR.
> Events timeouts extended

- event-log/src/main/scala/io/renku/eventlog/subscriptions/EventFetcher.scala
- helm-chart/renku-graph/Chart.yaml
- helm-chart/renku-graph/values.yaml
- version.sbt
This PR contains two tiny tweaks:
* memory limit raised for webhook-service to 2500Mi to prevent from unnecessary kube restarts
* MaxProcessingTime raised to 12 hours to prevent from same events being processed multiple times
> chore: webhook memory and maxProcessingTime increased

- event-log/src/main/scala/io/renku/eventlog/subscriptions/unprocessed/UnprocessedEventFetcher.scala
- version.sbt
It looked there was a bit of room for improving the performance of the `pop event - projects` query.
> Unprocessed fetch query

- event-log/src/main/resources/logback.xml
- knowledge-graph/src/main/resources/logback.xml
- token-repository/src/main/resources/logback.xml
- triples-generator/src/main/resources/logback.xml
- version.sbt
- webhook-service/src/main/resources/logback.xml
With the current set-up logback logs some status log entries on service start-up. This PR mutes that.
Example of logs to be muted:
```
15:02:36,161 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback-test.xml]
15:02:36,162 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback.groovy]
15:02:36,162 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Found resource [logback.xml] at [file:/Users/kuba/sdsc/code/renku-graph/webhook-service/target/scala-2.13/classes/logback.xml]
15:02:36,291 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - debug attribute not set
15:02:36,293 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type …
```
> fix: mute logback status log entries

- acceptance-tests/src/test/scala/ch/datascience/graph/acceptancetests/WebhookCreationSpec.scala
- acceptance-tests/src/test/scala/ch/datascience/graph/acceptancetests/stubs/GitLab.scala
- triples-generator/src/main/scala/ch/datascience/triplesgenerator/events/categories/awaitinggeneration/triplescuration/projects/GitLabInfoFinder.scala
- triples-generator/src/main/scala/ch/datascience/triplesgenerator/events/categories/awaitinggeneration/triplescuration/projects/ProjectPropertiesRemover.scala
- triples-generator/src/main/scala/ch/datascience/triplesgenerator/events/categories/awaitinggeneration/triplescuration/projects/UpdatesCreator.scala
- triples-generator/src/main/scala/ch/datascience/triplesgenerator/events/categories/awaitinggeneration/triplescuration/projects/UpdatesQueryCreator.scala
- triples-generator/src/main/scala/ch/datascience/triplesgenerator/events/categories/awaitinggeneration/triplescuration/projects/model.scala
- triples-generator/src/test/scala/ch/datascience/triplesgenerator/events/categories/awaitinggeneration/triplescuration/projects/GitLabInfoFinderSpec.scala
- triples-generator/src/test/scala/ch/datascience/triplesgenerator/events/categories/awaitinggeneration/triplescuration/projects/ProjectPropertiesRemoverSpec.scala
- triples-generator/src/test/scala/ch/datascience/triplesgenerator/events/categories/awaitinggeneration/triplescuration/projects/UpdatesCreatorSpec.scala
- triples-generator/src/test/scala/ch/datascience/triplesgenerator/events/categories/awaitinggeneration/triplescuration/projects/UpdatesQueryCreatorSpec.scala
- triples-generator/src/test/scala/ch/datascience/triplesgenerator/events/categories/awaitinggeneration/triplescuration/projects/package.scala
- version.sbt
I called this a fix because this was kind of a bug I think. 
closes #607
> fix: always upsert project name during triples transformation

- event-log/src/main/scala/io/renku/eventlog/metrics/StatsFinder.scala
- event-log/src/main/scala/io/renku/eventlog/subscriptions/EventsDistributor.scala
- event-log/src/main/scala/io/renku/eventlog/subscriptions/commitsync/CommitSyncEventFinder.scala
- event-log/src/test/scala/io/renku/eventlog/EventLogDataProvisioning.scala
- event-log/src/test/scala/io/renku/eventlog/metrics/StatsFinderSpec.scala
- event-log/src/test/scala/io/renku/eventlog/subscriptions/EventsDistributorSpec.scala
- event-log/src/test/scala/io/renku/eventlog/subscriptions/SubscriptionDataProvisioning.scala
- event-log/src/test/scala/io/renku/eventlog/subscriptions/commitsync/CommitSyncEventFinderSpec.scala
- version.sbt
This PR fixes the order of finding an event, marking it as taken and sending it to some subscriber so the event finding step happens only when there's a subscriber ready to accept an event.
> refactor: event distributor to fetch event when subscriber is up

- event-log/src/main/scala/io/renku/eventlog/subscriptions/zombieevents/LongProcessingEventFinder.scala
- event-log/src/main/scala/io/renku/eventlog/subscriptions/zombieevents/LostSubscriberEventFinder.scala
- event-log/src/main/scala/io/renku/eventlog/subscriptions/zombieevents/LostZombieEventFinder.scala
- event-log/src/main/scala/io/renku/eventlog/subscriptions/zombieevents/ZombieEventFinder.scala
- event-log/src/main/scala/io/renku/eventlog/subscriptions/zombieevents/ZombieNodesCleaner.scala
- event-log/src/test/scala/io/renku/eventlog/subscriptions/zombieevents/ZombieEventsFinderSpec.scala
- event-log/src/test/scala/io/renku/eventlog/subscriptions/zombieevents/ZombieNodesCleanerSpec.scala
**The problem**
It looks like it's possible that during deployment EL gets redeployed quicker than TGs get shut down. In such cases the old TGs, while still being up, can subscribe to the new EL and so they could never be removed from the `subscriber` table. As a consequence, events sent to such TGs would never be classified as zombies.
**Solution**
This PR changes the logic of the zombie subscription category so all rows from the `subscriber` table (including rows related to the active EL) get health tested and eventually removed.
> fix: zombie nodes to be removed irrespectively of the source

- event-log/src/main/scala/io/renku/eventlog/subscriptions/zombieevents/ZombieNodesCleaner.scala
- event-log/src/test/scala/io/renku/eventlog/subscriptions/zombieevents/ZombieNodesCleanerSpec.scala
**The problem**
After recent changes to the zombie nodes finding algorithm, some unnecessary ping calls to the EL service where the zombie finding exists were introduced. This is obviously not needed.
This PR checks if the given URL is the same as the service where the zombie finding process runs and skips pinging the service;
> fix: zombie nodes finder not to ping own service

- knowledge-graph/src/main/scala/ch/datascience/knowledgegraph/lineage/EdgesTrimmer.scala
- knowledge-graph/src/main/scala/ch/datascience/knowledgegraph/lineage/model.scala
- knowledge-graph/src/test/scala/ch/datascience/knowledgegraph/lineage/EdgesTrimmerSpec.scala
@gavin-k-lee found an issue with the lineage query when multiple files are used as both inputs and outputs to different Run Plans.
As an example, if we have lineage like follows:
```
m -- N -- o -- Q -- r
\_ p _/
```
because of the issue we'd produce:
```
m -- N -- o -- Q -- r
\_ p
```
> fix: lineage query to work with diamond cases

- .github/workflows/acceptance-tests.yaml
- .github/workflows/test-and-deploy.yml
- .github/workflows/test-and-publish.yml
It was identified that various GitHub different tokens (at least having different names) are used within the renku-graph repo. This PR removes usage of all the tokens except `RENKUBOT_GITHUB_TOKEN`.
> chore: switching to RENKUBOT_GITHUB_TOKEN

- event-log/src/main/scala/io/renku/eventlog/events/categories/commitsyncrequest/CommitSyncForcer.scala
- event-log/src/main/scala/io/renku/eventlog/subscriptions/commitsync/CommitSyncEventFinder.scala
- event-log/src/test/scala/io/renku/eventlog/events/categories/commitsyncrequest/CommitSyncForcerSpec.scala
- event-log/src/test/scala/io/renku/eventlog/subscriptions/commitsync/CommitSyncEventFinderSpec.scala
When picking up an AWAITING DELETION event, the last sync date will still be updated.
> fix: last sync date update

- acceptance-tests/src/test/scala/io/renku/graph/acceptancetests/tooling/ServicesRunner.scala
- commit-event-service/src/main/scala/io/renku/commiteventservice/Microservice.scala
- commit-event-service/src/test/scala/io/renku/commiteventservice/MicroserviceRunnerSpec.scala
- event-log/src/main/scala/io/renku/eventlog/Microservice.scala
- event-log/src/test/scala/io/renku/eventlog/MicroserviceRunnerSpec.scala
- graph-commons/src/main/scala/io/renku/events/consumers/EventConsumersRegistry.scala
- graph-commons/src/main/scala/io/renku/microservices/ServiceReadinessChecker.scala
- graph-commons/src/test/scala/io/renku/microservices/MicroserviceUrlFinderSpec.scala
- graph-commons/src/test/scala/io/renku/microservices/ServiceReadinessCheckerSpec.scala
- helm-chart/renku-graph/templates/triples-generator-deployment.yaml
- helm-chart/renku-graph/values.yaml
- triples-generator/src/main/resources/application.conf
- triples-generator/src/main/scala/io/renku/triplesgenerator/Microservice.scala
- triples-generator/src/main/scala/io/renku/triplesgenerator/reprovisioning/EventsReScheduler.scala
- triples-generator/src/main/scala/io/renku/triplesgenerator/reprovisioning/ReProvisionJudge.scala
- triples-generator/src/main/scala/io/renku/triplesgenerator/reprovisioning/ReProvisioning.scala
- triples-generator/src/main/scala/io/renku/triplesgenerator/reprovisioning/ReProvisioningStatus.scala
- triples-generator/src/main/scala/io/renku/triplesgenerator/reprovisioning/RenkuVersionPairFinder.scala
- triples-generator/src/main/scala/io/renku/triplesgenerator/reprovisioning/RenkuVersionPairUpdater.scala
- triples-generator/src/test/scala/io/renku/triplesgenerator/MicroserviceRunnerSpec.scala
- triples-generator/src/test/scala/io/renku/triplesgenerator/reprovisioning/ReProvisionJudgeSpec.scala
- triples-generator/src/test/scala/io/renku/triplesgenerator/reprovisioning/ReProvisioningSpec.scala
- triples-generator/src/test/scala/io/renku/triplesgenerator/reprovisioning/RenkuVersionPairFinderSpec.scala
Starting re-provisioning process in a separate thread is causing issues when there are multiple triples-generator instances running. This PR changes the behaviour so TG is not fully up until re-provisioning is not finished.
> fix: triples-generator to wait for re-provisioning

- .github/workflows/acceptance-tests.yaml
- .github/workflows/test-and-deploy.yml
- .github/workflows/test-and-publish.yml
So it seems there were renku actions published with the tag `0.5.0` which is missing the `v`. This caused the other automated PR to be automatically opened and then reviewed (where we missed the missing `v`) and merged.
This switches the actions back to using tags that contain `v` and a semver.
> chore(ci): Update renku action to v0.5.0

- event-log/src/main/scala/io/renku/eventlog/events/categories/statuschange/DBUpdateResults.scala
- event-log/src/main/scala/io/renku/eventlog/events/categories/statuschange/ToAwaitingDeletionUpdater.scala
- event-log/src/main/scala/io/renku/eventlog/events/categories/statuschange/ToFailureUpdater.scala
- event-log/src/main/scala/io/renku/eventlog/events/categories/statuschange/ToTriplesStoreUpdater.scala
- event-log/src/test/scala/io/renku/eventlog/events/categories/statuschange/DBUpdateResultsSpec.scala
- event-log/src/test/scala/io/renku/eventlog/events/categories/statuschange/ToAwaitingDeletionUpdaterSpec.scala
- event-log/src/test/scala/io/renku/eventlog/events/categories/statuschange/ToFailureUpdaterSpec.scala
- event-log/src/test/scala/io/renku/eventlog/events/categories/statuschange/ToTriplesStoreUpdaterSpec.scala
It looks like there are quite a few failures for the `EVENT_STATUS_CHANGE` events during re-provisioning. It would be good to the exceptions contains some more context. This PR adds the completion to the message.
> fix: failures for the status change event to log more details

- triples-generator/src/main/scala/io/renku/triplesgenerator/events/categories/triplesgenerated/projectinfo/MemberEmailFinder.scala
- triples-generator/src/test/scala/io/renku/triplesgenerator/events/categories/triplesgenerated/projectinfo/MemberEmailFinderSpec.scala
fix: switching users API to projects API for user matching
/deploy #persist
> fix: switching users API to projects API for user matching

- commit-event-service/src/main/scala/io/renku/commiteventservice/events/categories/commitsync/eventgeneration/CommitsSynchronizer.scala
- commit-event-service/src/main/scala/io/renku/commiteventservice/events/categories/commitsync/eventgeneration/LatestCommitFinder.scala
- commit-event-service/src/main/scala/io/renku/commiteventservice/events/categories/common/CommitInfoFinder.scala
- commit-event-service/src/main/scala/io/renku/commiteventservice/events/categories/globalcommitsync/eventgeneration/CommitsSynchronizer.scala
- commit-event-service/src/main/scala/io/renku/commiteventservice/events/categories/globalcommitsync/eventgeneration/gitlab/GitLabCommitFetcher.scala
- commit-event-service/src/main/scala/io/renku/commiteventservice/events/categories/globalcommitsync/eventgeneration/gitlab/GitLabCommitStatFetcher.scala
- commit-event-service/src/test/scala/io/renku/commiteventservice/events/categories/commitsync/eventgeneration/CommitsSynchronizerSpec.scala
- commit-event-service/src/test/scala/io/renku/commiteventservice/events/categories/commitsync/eventgeneration/LatestCommitFinderSpec.scala
- commit-event-service/src/test/scala/io/renku/commiteventservice/events/categories/common/CommitInfoFinderSpec.scala
- commit-event-service/src/test/scala/io/renku/commiteventservice/events/categories/globalcommitsync/eventgeneration/gitlab/GitLabCommitFetcherSpec.scala
- commit-event-service/src/test/scala/io/renku/commiteventservice/events/categories/globalcommitsync/eventgeneration/gitlab/GitLabCommitStatFetcherSpec.scala
It looks there are cases when we end up with some invalid access tokens for a project that is deleted. It looks it's safe for the sync processes to treat such cases as if the project is removed.
/deploy
> fix: commit sync processes to work with invalid access token

- generators/src/main/scala/io/renku/generators/Generators.scala
- triples-generator/src/main/resources/application.conf
- triples-generator/src/main/scala/io/renku/triplesgenerator/events/categories/triplesgenerated/EventProcessor.scala
- triples-generator/src/main/scala/io/renku/triplesgenerator/events/categories/triplesgenerated/projectinfo/MemberEmailFinder.scala
- triples-generator/src/test/scala/io/renku/triplesgenerator/events/categories/triplesgenerated/EventProcessorSpec.scala
- triples-generator/src/test/scala/io/renku/triplesgenerator/events/categories/triplesgenerated/projectinfo/MemberEmailFinderSpec.scala
- triples-generator/src/test/scala/io/renku/triplesgenerator/generators/ErrorGenerators.scala
It looks like the project's events GitLab API is pretty costly to call on projects with hundreds of events. The member email finding process tries to go through all the events causing a huge load on Postgres. This PR changes the logic so only first, middle and last 20 events will be checked.
> fix: member email finder not to traverse all project events if many

- event-log/src/main/scala/io/renku/eventlog/events/categories/statuschange/projectCleaner/ProjectWebhookAndTokenRemover.scala
- event-log/src/test/scala/io/renku/eventlog/events/categories/statuschange/projectCleaner/ProjectWebhookAndTokenRemoverSpec.scala
When removing a project it could happened that the token is not found at this point we can consider the project already removed and not throw an error
> fix: token removal error

- graph-commons/src/main/scala/io/renku/graph/http/server/security/DatasetIdRecordsFinder.scala
- graph-commons/src/main/scala/io/renku/graph/http/server/security/ProjectPathRecordsFinder.scala
- graph-commons/src/main/scala/io/renku/rdfstore/RdfStoreConfig.scala
- graph-commons/src/test/scala/io/renku/graph/http/server/security/AuthorizerSpec.scala
- knowledge-graph/src/main/scala/io/renku/knowledgegraph/projects/rest/GitLabProjectFinder.scala
- knowledge-graph/src/main/scala/io/renku/knowledgegraph/projects/rest/ProjectFinder.scala
- knowledge-graph/src/test/scala/io/renku/knowledgegraph/projects/rest/GitLabProjectFinderSpec.scala
- knowledge-graph/src/test/scala/io/renku/knowledgegraph/projects/rest/ProjectFinderSpec.scala
Currently, the `GET projects/:path` returns `500` if called with a valid access token although not for the project. Conversely, the resource works fine if you call it with no token at all. This PR makes both cases work the same.
> fix: GET projects/:path to work with any valid token if public project

- triples-generator/Dockerfile
- triples-generator/src/main/resources/application.conf
- triples-generator/src/main/scala/io/renku/triplesgenerator/events/categories/triplesgenerated/projectinfo/MemberEmailFinder.scala
- triples-generator/src/test/scala/io/renku/triplesgenerator/events/categories/triplesgenerated/projectinfo/MemberEmailFinderSpec.scala
This PR reduces the number of costly project's events endpoint on GitLab
> fix: member email finding algorithm to check up to 30 pages of project events

- triples-generator/src/main/scala/io/renku/triplesgenerator/events/categories/triplesgenerated/projectinfo/ProjectFinder.scala
- triples-generator/src/test/scala/io/renku/triplesgenerator/events/categories/triplesgenerated/projectinfo/ProjectFinderSpec.scala
It may happen that for public projects and invalid/no token in tokens-repository, the Transformation process will not get `visibility` back from the call to the Project Details GitLab API. It seems to be safe in such cases to default to `public` as if the project is non-public GitLab would respond with `404`.
> fix: Transformation to default to visibility public if not returned

- triples-generator/src/main/scala/io/renku/triplesgenerator/events/categories/membersync/GitLabProjectMembersFinder.scala
- triples-generator/src/test/scala/io/renku/triplesgenerator/events/categories/membersync/GitLabProjectMembersFinderSpec.scala
- triples-generator/src/test/scala/io/renku/triplesgenerator/events/categories/triplesgenerated/projectinfo/ProjectMembersFinderSpec.scala
It looks that the `401`s in the `MEMBERS_SYNC` flow causes two problems:
* they do not remove project members in KG of a project we cannot reason about (potentially some/all members of the projects are removed but as we cannot refresh the list, we keep the old one)
* create some noise in the logs
This PR applies a similar approach as in the other places to call the `/users` and `/members` endpoints without an access token. If that does not help, the process removes all the members from the TS.
If a project owner would like to bring the members back to the TS, it simply needs to log in to the UI and wait for the `MEMBERS_SYNC` process to refresh the list.
> fix: member-sync process to deal with 401s

- event-log/src/main/scala/io/renku/eventlog/subscriptions/eventdelivery/EventDelivery.scala
- event-log/src/test/scala/io/renku/eventlog/subscriptions/eventdelivery/EventDeliverySpec.scala
fix: adding twice the same delivery id should not throw an error
> fix: adding twice the same delivery id should not throw an error

- event-log/src/main/scala/io/renku/eventlog/events/categories/statuschange/ToFailureUpdater.scala
- event-log/src/main/scala/io/renku/eventlog/events/categories/statuschange/ToTriplesGeneratedUpdater.scala
- event-log/src/main/scala/io/renku/eventlog/events/categories/statuschange/ToTriplesStoreUpdater.scala
- event-log/src/test/scala/io/renku/eventlog/events/categories/statuschange/ToFailureUpdaterSpec.scala
- event-log/src/test/scala/io/renku/eventlog/events/categories/statuschange/ToTriplesGeneratedUpdaterSpec.scala
- event-log/src/test/scala/io/renku/eventlog/events/categories/statuschange/ToTriplesStoreUpdaterSpec.scala
It was found that in the case when there are two or more the most recent events that have the same date, one of them, not necessarily the latest event in terms of history, is picked up for processing. Thus, it's possible that the latest event is not processed at all but an assumption that it's one of the older events is taken. Obviously, in such case, the metadata in the KG is not complete.
> fix: events with the same date should be processed independently

- commit-event-service/src/main/resources/application.conf
- event-log/src/main/resources/application.conf
- graph-commons/src/main/scala/io/renku/config/sentry/SentryConfig.scala
- graph-commons/src/main/scala/io/renku/config/sentry/SentryInitializer.scala
- graph-commons/src/test/scala/io/renku/config/sentry/SentryConfigSpec.scala
- graph-commons/src/test/scala/io/renku/config/sentry/SentryInitializerSpec.scala
- graph-commons/src/test/scala/io/renku/generators/CommonGraphGenerators.scala
- helm-chart/renku-graph/templates/commit-event-service-deployment.yaml
- helm-chart/renku-graph/templates/event-log-deployment.yaml
- helm-chart/renku-graph/templates/knowledge-graph-deployment.yaml
- helm-chart/renku-graph/templates/token-repository-deployment.yaml
- helm-chart/renku-graph/templates/triples-generator-deployment.yaml
- helm-chart/renku-graph/templates/webhook-service-deployment.yaml
- helm-chart/renku-graph/values.yaml
- knowledge-graph/src/main/resources/application.conf
- token-repository/src/main/resources/application.conf
- triples-generator/src/main/resources/application.conf
- webhook-service/src/main/resources/application.conf
Apparently, the Sentry API has changed in some version and things like environment and service stopped to work. This PR fixes this.
> fix: Sentry initialization via the new API

- helm-chart/renku-graph/charts/jena/templates/fuseki-server.yaml
- helm-chart/renku-graph/charts/jena/templates/statefulset.yaml
It looks like Lucene indices in Jena get stale and so they don't return correct results. This PR removes them each time jena is restarted.
> fix: lucene indices to be deleted on each restart

- event-log/src/main/scala/io/renku/eventlog/events/categories/statuschange/projectCleaner/ProjectWebhookAndTokenRemover.scala
- event-log/src/test/scala/io/renku/eventlog/events/categories/statuschange/projectCleaner/ProjectWebhookAndTokenRemoverSpec.scala
> fix: the clean-up process not to log error for 401 on webhook removal

- event-log/src/test/scala/io/renku/eventlog/events/categories/zombieevents/EventHandlerSpec.scala
- triples-generator/src/main/scala/io/renku/triplesgenerator/events/categories/awaitinggeneration/triplesgeneration/renkulog/Commands.scala
- triples-generator/src/test/scala/io/renku/triplesgenerator/events/categories/awaitinggeneration/triplesgeneration/renkulog/GitSpec.scala
> fix: event of repos that cannot be cloned to be non-recoverable

- commit-event-service/src/test/scala/io/renku/commiteventservice/events/categories/commitsync/eventgeneration/LatestCommitFinderSpec.scala
- graph-commons/src/main/scala/io/renku/json/JsonOps.scala
- graph-commons/src/test/scala/io/renku/http/server/EndpointTester.scala
- knowledge-graph/src/main/scala/io/renku/knowledgegraph/MicroserviceRoutes.scala
- knowledge-graph/src/main/scala/io/renku/knowledgegraph/projects/rest/GitLabProjectFinder.scala
- knowledge-graph/src/main/scala/io/renku/knowledgegraph/projects/rest/ProjectEndpoint.scala
- knowledge-graph/src/main/scala/io/renku/knowledgegraph/projects/rest/ProjectFinder.scala
- knowledge-graph/src/test/scala/io/renku/knowledgegraph/projects/rest/GitLabProjectFinderSpec.scala
- knowledge-graph/src/test/scala/io/renku/knowledgegraph/projects/rest/ProjectFinderSpec.scala
refactor: 818 git lab client in kg
> refactor: git lab client in kg

- event-log/src/main/resources/application.conf
- event-log/src/main/scala/io/renku/eventlog/events/categories/globalcommitsyncrequest/EventHandler.scala
- event-log/src/main/scala/io/renku/eventlog/events/categories/globalcommitsyncrequest/GlobalCommitSyncForcer.scala
- event-log/src/main/scala/io/renku/eventlog/subscriptions/globalcommitsync/GlobalCommitSyncEventFinder.scala
- event-log/src/test/scala/io/renku/eventlog/events/categories/globalcommitsyncrequest/EventHandlerSpec.scala
- event-log/src/test/scala/io/renku/eventlog/events/categories/globalcommitsyncrequest/GlobalCommitSyncForcerSpec.scala
- event-log/src/test/scala/io/renku/eventlog/subscriptions/globalcommitsync/GlobalCommitSyncEventFinderSpec.scala
It looks like global commit sync does not work correctly for big projects being updated often. That's due to `statistics.commits_count` returned by the call to the single project GitLab API does not get updated instantly after a new commit is pushed. This PR changes the global commit sync request logic so instead of issuing the `global_commit_sync` event instantly, the event is scheduled in 5 mins.
> fix: global commit sync to be set in 5 mins on forcing
